### ISSUE TITLE
Rendre plus visible la possibilité de faire une propostions de post

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#100]
Suite à ce commentaire https://github.com/putaindecode/website/issues/98#issuecomment-30602151 il faut éclairsir le repo dédié aux propostions de posts

**Comment by madx** [comment]
On s'en fout on ne se sert plus du repo de propositions de posts

**Comment by MoOx** [comment]
Cela dit je pense qu'il faut clairement mettre plus en avant le fait que les gens puisse proposeer des posts, on en a eu trop peu. Je réouvre et renomme.

**Comment by MoOx** [comment]
Closing in favor of #531
