### ISSUE TITLE
Refaire une 404 plus sympa

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#107]
Et centré tant qu'à la refaire.

**Comment by MoOx** [comment]
Des idées ?

En l'état http://putaindecode.fr/404

**Comment by bloodyowl** [comment]
how 'bout something like that http://jsbin.com/podefaxuko/1/edit?html,js,output

**Comment by kud** [comment]
Peut-être @bloodyowl mais sans pour autant être grossier.

**Comment by madx** [comment]
L'actuelle ne me dérange pas, en tous cas je pense que c'est pas le plus
urgent

Le 9 mai 2015 12:23, Erwänn Mest <notifications@github.com> a écrit :

> Peut-être @bloodyowl <https://github.com/bloodyowl> mais sans pour autant
> être grossier.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/putaindecode/putaindecode.fr/issues/107#issuecomment-100461680>
> .
>



-- 
François Vaux
http://madx.me/

**Comment by MoOx** [comment]
Closing in favor of #497
