### ISSUE TITLE
emoji support

### ISSUE THREAD

**Issue by bloodyowl** [putaindecode/putaindecode.io#187]
ajouter un vrai support emoji (notamment pour les utilisateurs windows)

**Comment by MoOx** [comment]
Switching to markdown-it planned.

https://github.com/markdown-it/markdown-it-emoji

**Comment by kud** [comment]
Fun. :D

**Comment by MoOx** [comment]
Do we still need to handle this? I guess browsers should (firefox already works great with emoji)

**Comment by MoOx** [comment]
Browsers are handling that now, so I guess we won't do anything...
