### ISSUE TITLE
Contraste sur les liens

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.io#198]
Ouais, je suis légèrement daltonien et euh... le contraste sur les liens est mauvais, je ne les vois pas facilement.

Pourrait-on améliorer cela ? J'ai pas trop d'idée pour le moment.

**Comment by MoOx** [comment]
C'est toujours un  problème ?

**Comment by kud** [comment]
Oui. Le rouge n'est pas assez prononcé ou est trop sombre et j'ai du mal à le distinguer du noir. Peut-être mettre un rouge plus clair.

**Comment by bloodyowl** [comment]
si on le met plus clair on aura des soucis de contraste avec le fond, donc d'autres problèmes de vue non pris en compte. on ajoute un underline et c'est réglé?

**Comment by kud** [comment]
Underline pourquoi pas oui.

**Comment by lionelB** [comment]
underline me parait pas mal

**Comment by MoOx** [comment]
Du coup je pense que une petite pr pour ça doit pas prendre trop de temps :)

**Comment by kud** [comment]
Oui carrément @MoOx, je vais voir dès que j'ai un peu de temps pour ça. Je m'affecte la tâche.

**Comment by MoOx** [comment]
Feel free to make a PR.
