### ISSUE TITLE
Intégration headroom.js ?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#239]
http://wicky.nillia.ms/headroom.js/

**Comment by MoOx** [comment]
up

**Comment by kud** [comment]
Toujours intéressant à mon sens.

**Comment by MoOx** [comment]
https://github.com/cssnext/cssnext/commit/eef9a298d460b931740a581501879bd9d3dbd15f
En ligne mercredi sur le site de cssnext :)

**Comment by MoOx** [comment]
Hop en exemple http://cssnext.io/features/

**Comment by kud** [comment]
J'adore !

On 17 June 2015 at 15:10, Maxime Thirouin <notifications@github.com> wrote:

> Hop en exemple http://cssnext.io/features/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/putaindecode/putaindecode.fr/issues/239#issuecomment-112794028>
> .
>



-- 
*Erwann Mest*
kud.io

**Comment by lionelB** [comment]
niquel @MoOx

**Comment by MoOx** [comment]
Not a priority atm.
