### ISSUE TITLE
Les espaces insécables ne sont pas interprétés

### ISSUE THREAD

**Issue by Macxim** [putaindecode/putaindecode.io#314]
Exemple ci-dessous :
![img_3207](https://cloud.githubusercontent.com/assets/1909957/4897813/b5f5e2b4-6409-11e4-9a0b-d071e44514a9.PNG)

**Comment by MoOx** [comment]
Interesing project https://github.com/sapegin/richtypo.js

**Comment by Macxim** [comment]
Very interesting I'd say. Thanks for sharing! :+1:
