### ISSUE TITLE
proposition de séries de post sur l'intégration continue

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#332]
- [x] L'intégration continue c'est quoi?
- [x] Le déploiement continue
- [ ] Mise en place d'intégration continue avec Travis-CI (*nix)
- [x] Deployer un projet sur GitHub Pages via Travis-CI
- [ ] Mise en place d'intégration continue avec AppVeryor (windows)
- [ ] Mise en place de tests d'UI automatisés dans tous les navigateurs avec Testem
- [ ] Execution de tests d'UI automatisés avec SauceLab via Travis-CI

**Comment by Nyalab** [comment]
Fais attention à ne pas trop vouloir en faire, tu peux faire quelques posts avec plusieurs grandes parties pour pas t'essouffler et passer 20 ans sur le même sujet (sans doute que toi à côté tu seras passé à autre chose en plus).

Sinon, :+1:

**Comment by MoOx** [comment]
J'ai déjà un putain de brouillons avec 3/4 parties :)
Je compte vraiment faire des posts courts.

**Comment by drazik** [comment]
Très intéressé par le sujet. Ca manque de ressources concrètes sur le web je trouve.

**Comment by Macxim** [comment]
Ça m'intéresse beaucoup aussi. :+1:

**Comment by angezanetti** [comment]
:+1:  aussi !

**Comment by magsout** [comment]
:+1:

**Comment by magsout** [comment]
up, t'avais un gist de tout prêt en plus ?

**Comment by MoOx** [comment]
Oui ça va venir ;) Y'a déjà 2/3 posts en PR donc je push ça après.

**Comment by magsout** [comment]
coool

**Comment by lionelB** [comment]
super !

**Comment by MoOx** [comment]
On va dire que c'est bon là, je verrais pour le reste plus tard.
