### ISSUE TITLE
Ajouter des index des catégories

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#344]
Ouais y'a des issues en anglais, d'autres en français, c'est la fête du slip.

Bon je pense à ça depuis un moment, mais ça serait vraiment pas mal de faire des index manuels des catégories. Ca demande un petit boulot éditorial, mais ça serait vraiment bien. Un point d'entrée intéressant et commenté. On pourrait ainsi rajouter en référence des posts externes comme http://www.splitfire.fr/blog/article/gerer-vos-modules-avec-npm (coucou @magsout - ref https://github.com/putaindecode/propositions-de-posts/issues/62 ).

**Comment by magsout** [comment]
Ouais alors j'avais pas vu ton issue https://github.com/putaindecode/propositions-de-posts/issues/62

> des index manuels des catégories

Par contre j'ai pas compris.

**Comment by MoOx** [comment]
En gros on fait des pages à la racines des /posts/{cat}

Genre /posts/js/(index.html) on on pose un petit blabla sur le JS et on y liste (avec sens) tous les posts qu'on a écrit (ou qui ont été écrit ailleurs faute de ressources chez nous) afin de proposer de bonnes pistes. Vous en pensez quoi ?

**Comment by magsout** [comment]
Ah, bonne idée je trouve

**Comment by magsout** [comment]
poke @putaindecode/owners

**Comment by MoOx** [comment]
Ils ont déjà été poké. Ne t'en fais pas on le fera.
Pour moi quand je fais une proposition, sans réponse sous quelques jours je considère que personne n'a d'objections. Puis si les gens en ont, il nous ferons signe.

Note: on attendra la version react pour se lancer là dedans. Il faudra en fait update ensuite la doc sur la rédaction des posts et chaque post devra figurer dans les index: soit manuellement pour être éventuellement mis en avant, soit automatiquement si pas fait manuellement.
Je vois bien une partie texte sur chaque index + listing auto des posts non linké dans la partie blabla. Dans un premier temps ça sera bien.

**Comment by magsout** [comment]
ouip nickel..

**Comment by lionelB** [comment]
ça serait top meme, à voir si on arrive à le maintenir dans le temps

**Comment by MoOx** [comment]
https://github.com/MoOx/statinamic/issues/15 can help
