### ISSUE TITLE
Ajouter des notes sur les articles dépréciés

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#351]
Chaque dépréciation devra passer par une PR, avec une explication sur le pourquoi et surtout un lien vers une ressource plus à jour.
Un documentation sur ce processus devra aussi être ajouté pour ne pas oublié quand et comment faire ça.

**Comment by kud** [comment]
obsolètes*

**Comment by magsout** [comment]
:+1: comme dit sur irc

**Comment by MoOx** [comment]
Le post sur grunt n'est pas obsolète dans le sens où plein de gens se mettent à grunt. Par contre nous pouvons prendre l'avis de déprécier un post en faveur d'une ressource plus récente. J'ai donc volontairement utilisé déprécié (depreciated et non deprecated donc).

**Comment by lionelB** [comment]
bien vu :+1:
