### ISSUE TITLE
Remplacer Disqus

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#356]
La pub va arriver, hors de question qu'on est une pub non sollicité par les @putaindecode/owners 
On va tranquillement voir comment virer tout ça.

https://business.disqus.com/blog/disqus-launches-global-programmatic-native-advertising/

**Comment by MoOx** [comment]
J'ajoute une note car @kud n'aime pas que "je prenne des décisions seul".
Selon moi, si y'a de la pub sur ce site, c'est avec les conditions suivantes:
- totale controle par l'équipe édito
- rémunération des auteurs au pro-rata + dispatch pour d'eventuelles frais (nom de domaine + server si on devrait en avoir un).

**Comment by madx** [comment]
:+1:

**Comment by kud** [comment]
Je suis d'accord avec ça !

Allez, sujet clos, on vire cette merde.

**Comment by dguyon** [comment]
Idéalement, ca serait mieux sans publicités...

**Comment by magsout** [comment]
:+1:  , on vire

**Comment by MoOx** [comment]
On clos pas le sujet, on l'ouvre @kud. Il faut réfléchir:
- alternative sans pub
- trouver une soluce open source (cela pourra nécessiter un serveur).

**Comment by kud** [comment]
Faut tout cramer. Pas de commentaire, c'est pour les faibles. De toute facon, y'a rien à rajouter à nos posts, ils sont PAR-FAITS.

**Comment by Nyalab** [comment]
Ouais, enfin, on utilise twitter pour @putaindecode et y'a exactement le même type de pub

**Comment by kud** [comment]
Et on a un groupe facebook.

**Comment by magsout** [comment]
@Nyalab sauf que nos articles sont pas en lecture  sur twitter.

**Comment by MoOx** [comment]
@bloodyowl a proposé ça http://web.livefyre.com/apps/comments/

**Comment by dguyon** [comment]
:+1:

**Comment by magsout** [comment]
je connais pas, pourquoi pas.

**Comment by kud** [comment]
Un peu dans la même idée. A méditer.
http://framablog.org/2015/03/13/google-code-ferme-ses-portes-nous-on-les-ouvre/

**Comment by MoOx** [comment]
Idea https://github.com/MoOx/statinamic/issues/312

**Comment by MoOx** [comment]
Je pose ça là. https://staticman.net/docs/

**Comment by bloodyowl** [comment]
osef for now
