### ISSUE TITLE
post es6

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#366]
@Nyalab ETA ?

**Comment by Nyalab** [comment]
moi on m'a dit de rien pousser ; une fois que je pourrais, sous 2 semaines max, j'ai le post d'intro + le post sur les variables. le reste des posts sera en suivant.

**Comment by MoOx** [comment]
tu peux déjà pousser un .md par là qu'on review ^^.
Le site arrivera plus vite que vous croyez ;)

**Comment by lionelB** [comment]
+1 avec moox je pense qu'il vaut mieux avoir des post pret à être publier

**Comment by Nyalab** [comment]
bah on m'avait dit de rien pousser, moi j'obéis, si c'est ok, je me remets à bosser le post d'intro et finaliser le premier sur les vars :muscle:

**Comment by MoOx** [comment]
No comment.

**Comment by Nyalab** [comment]
:trollface:
