### ISSUE TITLE
Faire des build online par PR

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#367]
Vous penseriez quoi de push les PRs sur un sous domaine qu'on puisse visualiser le résultat avant de merger ?
Si on pousse ca sur un repo pr.putaindecode.fr on devrait pouvoir faire un truc genre pr.putaindecode.fr/345/{le site de la pr}

**Comment by kud** [comment]
N'est-ce pas suffisant de récupérer le projet et tester en local ? Faut-il vraiment un staging ?

**Comment by MoOx** [comment]
Perso je n'ai jamais récupérer une PR en cli. Je trouve ça lourd, surtout si c'est une PR forké.

**Comment by kud** [comment]
D'accord. Dans ce cas là, pourquoi pas oui.

**Comment by bloodyowl** [comment]
juste penser à mettre un robots.txt en nofollow

**Comment by MoOx** [comment]
Ouais clairement :) avec du rel=nofollow partout pour être sur :D

**Comment by kud** [comment]
J'avoue que là, étant sous Windows (bouuuuuh) et n'ayant pas envie de m'emmerder à compiler lorsque j'écris un article, un 'tit staging serait pas désagréabl.

**Comment by MoOx** [comment]
I have think about it, should be very easy. We should make a domain like "pr.putaindecode.io".

**Comment by bloodyowl** [comment]
nice to have mais pas essentiel pour l'instant, closing

**Comment by MoOx** [comment]
netlify allow this, so #568 will help :)
