### ISSUE TITLE
code highlight theme

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#37]
Il nous faut un theme sympa qui colle avec le site. 

Voilà ce que j'ai sous la main 

![screen shot 2013-10-18 at 5 21 17 pm](https://f.cloud.github.com/assets/157534/1361516/04e966bc-3809-11e3-8ce7-f74abb744d52.png)

![](https://github.com/MoOx/sass-prism-theme-base/blob/master/screenshot.png?raw=true)

![](https://github.com/MoOx/sass-pygments-theme-base/raw/master/pygments-theme-freshcut.png)

Sinon mettez ici votre propal, ou juste un theme de couleur si vous avez que ça :)

**Comment by X-Raym** [comment]
Salut à tous,
Il semblerait que la colorisation synthaxique du code ne soit plus présente,
le fichier _highlight.scss cité plus haut est d'ailleurs absent de la branche Master,

Je pense qu'il serait bon de restaurer cette fonctionnalité afin d'améliorer la lecture des code snippets, en particulier si ils sont un peu long.

Merci pour votre écoute 👍

**Comment by MoOx** [comment]
@X-Raym le fichier a juste été déplacé. C'est un bug lié au moteur, je corrige ça rapidement.

**Comment by X-Raym** [comment]
@MoOx Parfait, le code est beaucoup plus lisible :P Merci !
