### ISSUE TITLE
proposition de post sur le SVG

### ISSUE THREAD

**Issue by magsout** [putaindecode/putaindecode.io#400]
### 2) definitions des attributs :
- `viewbox` 
- `preserveAspectRatio` (slice meet, xMin etc...)
### 3) comment utiliser le svg
- avec la balise image
- avec la proprieté background
- inline
### 5) utiliser SVG pour ajouter des filtres à une image.

Les points 2 et 5 sont des choses que j'ai appris récement, le reste fait peut-être un peu old ?

**Comment by kud** [comment]
Oui c'est pas mal. :)

Il faudrait aussi l'expliquer je pense l'avantage d'utiliser l'svg par rapport aux autres formats, rapidement hein, pas s'étaler.

**Comment by magsout** [comment]
oui tu as raison alors, à ajouter en début.

>### 1) Petite def sur le svg 

### 1) Petite def sur le svg et ses avantages

**Comment by kud** [comment]
Old possible mais certains ont pas encore passé le cap du SVG donc je pense que ca reste intéressant. (sauf si tu veux faire un post court). Sinon tu peux éventuellement mettre des liens vers des sites qui l'expliquent au pire.

Carrément pour développer les 2/ et 5/ par contre.

**Comment by MoOx** [comment]
+1 pour la propal dans sa globalité. Faut pas non plus faire un pavé je pense, sinon ça va être lourd. Si besoin découper en plusieurs posts.

**Comment by Nyalab** [comment]
carrément pour, je suis de ceux qui n'ont pas passé le cap du svg "conceptuellement", un article bien expliqué peut être sympa :+1:

**Comment by lionelB** [comment]
:+1:

**Comment by kud** [comment]
C'en est oooooooooù ? On attend nous :p

**Comment by magsout** [comment]
ah oui, oupss, j'en ai fait un autre entre temps. J'ai zappé en vérité. Bon j'attaque alors.

**Comment by kud** [comment]
:)

**Comment by MoOx** [comment]
poke @magsout

**Comment by Uhsac** [comment]
Would love to read this article ! :smiley:

**Comment by magsout** [comment]
ouip... Il faut.

**Comment by bloodyowl** [comment]
@magsout tu penses avoir le temps bientôt pour gérer ça ou je close ?

**Comment by magsout** [comment]
@bloodyowl yes, compte sur moi
