### ISSUE TITLE
Définir et respecter un workflow d'intégration/review/correction des posts

### ISSUE THREAD

**Issue by madx** [putaindecode/putaindecode.io#401]
tl;dr: On rebase + squash tous les commits d'une branche `post.` ou on garde l'historique et on merge ?
## Le problème

Actuellement, une fois qu'on passe en revue un post, on se retrouve avec le commit initial, des commits des relecteurs pour corriger quelques typos + éventuellement d'autres commits de l'auteur original qui retravaille son post.

C'est bien, c'est pratique, ça permet de savoir qui fait quoi et quand, mais par contre au niveau de l'historique ça peut potentiellement être un peu fouillis quand on veut chercher une information sur un changement précis.
## Alternative 1

On garde le process de revue bordélique tel qu'il est actuellement mais qui fonctionne bien car chacun peut faire ses corrections ou commenter le texte du post directement pour que l'auteur les fasse. Avant publication, on demande à l'auteur de squasher tous les commits en un seul et de les rebaser sur le dernier master avant de valider la PR. Au final on se retrouve avec un commit tout propre et sans entrelacs de branche vu qu'il y a eu le rebase
## Alternative 2

On garde tout l'historique tel qu'il est tout en demandant à l'auteur de rebaser sur le dernier master pour éviter les entrelacs de branches. Puis validation de la PR comme d'hab.
## Alternative 3

On ajoute un champ "auteurs" dans les posts pour ne pas avoir à gérer un script qui va savoir qui a commité sur tel ou tel fichier. C'est plus lourd à l'utilisation et on risque d'oublier des gens, mais ça nous permet de tout squasher sans perde l'information de qui a participé à un post.

Je vous laisse développer vos idées

**Comment by madx** [comment]
Perso je penche en faveur de la deuxième alternative mais par contre j'aimerais qu'on arrête de commenter les posts pour montrer les typos à l'auteur, c'est complètement con et c'est une perte de temps car faire un commit pour corriger directement (via l'interface web de GH par exemple) va tout aussi vite et est beaucoup plus productif.

Après, je pense qu'un rebase+squash peut être sélectif et permettre de garder les informations de qui fait des modifications. Si on gère bien on pourrait faire en sorte de ne laisser qu'un commit de corrections par contributeur au post, ça garde un historique léger et permet de savoir qui a apporté quelle modif.

Wala

**Comment by MoOx** [comment]
> Alternative 2

Ou Alternative 3 avec un champs "contributors"

A noté que de toute façon, on aura toujours des commits "typo" ne serait-ce que de gens qui interviennent après publication d'un post. Donc pour moi j'ai un peu envie de dire "osef de la taille de l'historique".

Sinon à la limite si ça vous chagrine, on fait un repo avec le contenu, un repo avec les sources du sites. Mais dans la partique je sens que ça va être relou.

> par contre j'aimerais qu'on arrête de commenter les posts pour montrer les typos à l'auteur, c'est complètement con et c'est une perte de temps car faire un commit pour corriger directement (via l'interface web de GH par exemple) va tout aussi vite et est beaucoup plus productif.

+ 100000. Je propose même qu'on kick/ban les gens qui feront ça si on s'est tous mis d'accord là dessus et que quelqu'un le refait. Un commit via l'interface GH est pas plus lourd. SAUF POUR LES POSTS DE GENS EXTERNES (pour l'instant on en a pas trop mais qui sait...).
Sinon en cas de review pour post externe ou on peut pas commit, on fait un comment avec des quotes et des fix dessous pour éviter les 32 notifs (car de toute facon dans la pratique, intégrer les fix lignes par lignes c'est relou, tu dois te taper chaque comment, regarder le numéro de la ligne, puis corriger dans ton post...)

> Après, je pense qu'un rebase+squash peut être sélectif et permettre de garder les informations de qui fait des modifications. Si on gère bien on pourrait faire en sorte de ne laisser qu'un commit de corrections par contributeur au post, ça garde un historique léger et permet de savoir qui a apporté quelle modif.

Moi je dis qu'on se fait pas chier, pour l'instant on a jamais eu de problèmes à cause de la situation actuelle. Je vois pas pourquoi dans le fond faut amener du changement si y'a aucune raison valable (aucun problème sous jacent).

**Comment by magsout** [comment]
>Alternative 3

Ouip, ça peut-être pas mal efffectivement. Sauf que comme l'a dit @MoOx il y aura toujours le cas des PR ... 
Le systeme actuel me pose pas de problème. Ca me dérange pas d'avoir un post avec plusieurs commits et les contributeurs, même si l'article n'est pas encore sortie.

**Comment by bloodyowl** [comment]
> par contre j'aimerais qu'on arrête de commenter les posts pour montrer les typos à l'auteur, c'est complètement con et c'est une perte de temps car faire un commit pour corriger directement

au moins ça permet de discuter d'une tournure de phrase ou d'un fix avant de faire une connerie IMO.

**Comment by MoOx** [comment]
Pour le coup @kud parlait plus imo des typo purs et simples. Evidement quand on veut modifier une tournure ou plus qu'une faute d'orthographe ou de grammaire évidente, on passe par un comment sur la pr.

**Comment by kud** [comment]
Je ne suis pas toujours devant mon poste de dev et faire des commits via autre chose que l'interface de github ne m'est pas possible.

Effectivement, on peut patcher maintenant assez facilement via le site en créant soit une branche soit en rajoutant direct un commit sur la branche. Cependant comme le dit @bloodyowl, ca permet de discuter de certaines tournures de phrases et autre.

Je suis d'accord sur le fait que pour l'auteur, c'est pas super agréable pour se corriger lorsque qu'il y a des commentaires mais les commentaires, j'ai envie de dire, c'est à prendre ou à laisser contrairement au commit où y'a eu vraiment une volontée de corriger.

Je suis pour le moment pour l'alternative 2, et pour laisser le choix aux utilisateurs de corriger comme ils le souhaitent, soit via une PR/un commit soit via des commentaires.

**Comment by madx** [comment]
Oui, j'ai pas été assez clair mais les commentaires quand il s'agit de discuter d'une tournure, c'est mieux. Par contre pour de pures typos, aucun intérêt.

**Comment by Nyalab** [comment]
whatever you want, le gros historique osef, au moins on peut blame et sinon comme vous voulez, je ferais avec

**Comment by MoOx** [comment]
En gros on à tous l'air ok pour

- typos évidente: commit directement
- remise en question: comment inline

**Comment by kud** [comment]
Je pense oui @MoOx.

**Comment by Nyalab** [comment]
oui, mais pas de rebase+squash en un seul commit à la fin imho, garder un historique qui reflète la réalité c'est mieux, puis c'est pas comme si un historique git était si lourd...

**Comment by kud** [comment]
Contrairement à la vie réelle, on a le pouvoir de réécrire l'histoire, c'est pas pour rien. :p

**Comment by Nyalab** [comment]
squasher 3 commits de typo en un seul oui, ok, réécrire l'histo de l'auteur + 3 reviewers nan (à débattre bien sur, mais c'est mon avis)

**Comment by kud** [comment]
C'est plus pour les typos que ça me gène, pas les contributors qui ajoutent du texte en fait.

1/ L'auteur passe un peu pour un con à faire plein de fautes
2/ Quel intérêt de garder les commits de typo ?

**Comment by MoOx** [comment]
>  L'auteur passe un peu pour un con à faire plein de fautes

Perso j'assume totalement mes fautes. Y'a pas de honte à avoir. On écrit un post, on met pas tous nos casquettes bernard pivot quand on a déjà celle du dév puriste.

> Quel intérêt de garder les commits de typo ?

Un mec qui corrige un typo, c'est un contributeur à l'article. Y'a pas de petites contributions. Je pense que la réfléxion est aussi simple et ne dois pas aller plus loin. De toute façon je répète, on aura toujours des commits de typos après la publication, donc pourquoi s'emmerder avant sachant qu'on aura toujours le problème...

**Comment by kud** [comment]
Donc https://github.com/putaindecode/putaindecode.fr/issues/401#issuecomment-100815863, on est tous bon sur ça ?

**Comment by madx** [comment]
Oui, je pense que ça déjà on est tous d'accord

Pour le reste, on essaye d'avoir des branches de post un poil + propres sans pour autant niquer tout l'historique, après les merge font le job, ça vous va ?

Il faut aussi surtout rappeler de rebaser avant de valider un PR pour éviter les entrelacs dans l'historique (c'est ça la + moche à mon sens)

**Comment by MoOx** [comment]
Faut documenter ça du coup :)

**Comment by Macxim** [comment]
L'alternative 2 me paraît également être la meilleure.
> typos évidente: commit directement
> remise en question: comment inline

D'accord aussi avec ceci. C'est d'ailleurs ce que j'ai fait je crois pour le dernier post de @kud.

**Comment by magsout** [comment]
Donc :

**Comment by MoOx** [comment]
lol @magsout

**Comment by magsout** [comment]
@MoOx fail du raccourci ;p

**Comment by MoOx** [comment]
Et si on rajoutais aussi la règle 

- During a review, the 3rd person which is ok might change review label on the PR.

**Comment by kud** [comment]
Il y a une discussion à faire : quid des corrections de PR venant d'un autre repo ?

Est-ce possible de les commenter quand c'est des typo, ou faut vraiment faire une PR sur le repo du mec à cette PR ?

**Comment by MoOx** [comment]
PR sur PR, c'est pas plus long, ne serait-ce que via GitHub. Après ça peut être relou je comprends bien.

**Comment by kud** [comment]
Je pense que pour les articles devant de l'extérieur, on devrait faire comme bon nous semble.

En revanche, lorsqu'il s'agit d'un post interne : 

- typo -> commit direct
- discussion -> un commentaire

Pour les contributions des autres sur un post, c'est cool mais je ne vois pas l'intérêt de garder le commit. Je pense qu'un seul commit devrait suffir pour un post. Si en revanche, vous voulez vraiment les garder, je ferai attention à ne faire aucune faute pour n'avoir qu'un commit. :D

**Comment by MoOx** [comment]
Je propose aussi qu'on fasse en 2 temps:

- need revision: relecture sur le fond (ici l'auteur peut force push et tout, perdant tous les commits)
- need final revision: relecture sur la forme, c'est là qu'on peut corriger les typos et autres trucs via commit directe (ici on ne doit plus force pusher, afin de conserver les éventuelles contributions - même les fautes selon moi, nécessite un petit merci via l'affichage en temps que contributeur)

Je n'aime pas l'idée qu'on perde trace de contributions comme ça a déjà été le cas. L'histo on s'en branle un peu qu'il soit propre, par contre il sert pour voir qui fait quoi, et ça me semble plus important.

**Comment by kud** [comment]
Carrément une bonne idée, j'aime bien.

En effet, je suis partagé sur le nombre de commits, j'aime bien que ce soit propre et minimaliste. On publie une "fonctionnalité" en faisant un post, pas 36. Et en même temps, j'aimerais remercier la relecture des personnes. Pour le moment, ça se fait (malheureusement/heureusement) via commits.

En proposant le 2-steps comme tu présentes, cela répond bien à tous les problèmes. :+1:  donc.

**Comment by Nyalab** [comment]
![](http://cdn.meme.am/instances/500x/57634473.jpg)

**Comment by bloodyowl** [comment]
bikeshedding
