### ISSUE TITLE
Proposition de post: nvm

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#406]
Expliquer pourquoi iojs.
Puis en gros

`brew install nvm && mkdir $HOME/.nvm && nvm install iojs && nvm alias default iojs`

Ça inclue un petit topo nvm (on fait un post avant ?)

**Comment by kud** [comment]
Je valide le post initial + la présentation de nvm. ;)

**Comment by MoOx** [comment]
On linux madx did

```console
$ git clone https://github.com/creationix/nvm.git ~/.nvm && cd ~/.nvm && git checkout git describe --abbrev=0 --tags
$ nvm install iojs && nvm alias default iojs
```

**Comment by madx** [comment]
Pour l'installation de NVM: https://github.com/creationix/nvm#installation

Après il faut ajouter `. ~/.nvm/nvm.sh` dans son `.bashrc` et suivre les instructions de @MoOx

**Comment by magsout** [comment]
Carrément :+1: 

D'ailleurs je suis tombé la-dessus ce matin https://raygun.io/blog/2015/05/performance-showdown-node-js-vs-io-js-v2-0-0/

**Comment by MoOx** [comment]
node. is. dead. :/

**Comment by MoOx** [comment]
Bon en fait io.js et node.js vont merge. On verra quand y'aura du nouveau.

**Comment by magsout** [comment]
Oh ? T'as vu ça ou ?

**Comment by magsout** [comment]
Au final autant continuer avec node directement ?

**Comment by kud** [comment]
Comment ça ils vont merger ?

On 14 May 2015 at 20:34, Guillaume Demesy <notifications@github.com> wrote:

> Au final autant continuer avec node directement ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/putaindecode/putaindecode.fr/issues/406#issuecomment-102129265>
> .
>



-- 
*Erwann Mest*
kud.io

**Comment by MoOx** [comment]
https://github.com/iojs/io.js/issues/1664#issuecomment-101828384

**Comment by kud** [comment]
Cooool ça.

**Comment by MoOx** [comment]
> iojs GitHub org has been renamed to nodejs.

https://twitter.com/mikeal/status/599261550528991232

https://github.com/nodejs/io.js

**Comment by magsout** [comment]
Et Node dans tout ça ? Ils vont merged ?

**Comment by MoOx** [comment]
Oui c'est la finalité je pense. io.js va devenir le nouveau nodejs quoi. io.js a tout intérer à se renommer.

**Comment by Macxim** [comment]
:+1: pour le post. Ça va aider les n00bs comme moi. Merci.

**Comment by kud** [comment]
C'est vraiment pas plus mal. Je voyais mal deux "node", le bordel que c'aurait foutu.

**Comment by Nyalab** [comment]
bof pour le post, maintenant que ça merge osef, peut être faire un post mémorial lol
par contre 2 moteurs d'exécution js server-side je vois pas le souci @kud, y'en a bien plusieurs en front

**Comment by MoOx** [comment]
Ouais le merge arrive. On a juste à attendre un peu :)

**Comment by kud** [comment]
Parce que certaines libs ne marchent qu'avec l'un ou qu'avec l'autre. Tu aurais dû utiliser nvm. Perso, ca me casse les couilles.

Autant _, ca passe, autant là…

**Comment by Nyalab** [comment]
bah c'est comme des features que t'as que dispo sous chrome, la preuve, ça force la concurrence (firefox en a bénéficié) et la preuve nodejs va en bénéficier, même si ça avait pas mergé, nodejs aurait du se réveiller pour se mettre à niveau :)

**Comment by kud** [comment]
Je suis pas d'accord avec le // de ta phrase mais je n'ai pas le temps de développer.

**Comment by MoOx** [comment]
Moi je suis d'accord et je n'ai pas le temps de développer.
Si iojs n'avait pas été, on serait encore avec un node 0.10. Seriously. Stop le touchage de bite.

**Comment by kud** [comment]
Je dis pas que iojs n'a pas sa place. Je dis simplement que je suis content qu'il n'en reste plus qu'un et que ce soit iojs.

**Comment by Nyalab** [comment]
en effet, le dénouement est cool, tout le monde va en profiter

**Comment by skinnyfoetusboy** [comment]
Ça veut dire qu'on pourra builder Putaindecode sans passer par io.js maintenant ? :trollface:

**Comment by MoOx** [comment]
Je réouvre en tant que post pour nvm :)

**Comment by bloodyowl** [comment]
osef now
