### ISSUE TITLE
Augmenter l'interlignage des h*

### ISSUE THREAD

**Issue by kewah** [putaindecode/putaindecode.io#423]
![screen shot 2015-05-22 at 09 21 09](https://cloud.githubusercontent.com/assets/195442/7765958/49334318-0064-11e5-8416-f608f67ef19a.png)

Les lettres se touchent, c'est pas jolie et c'est perturbant :)

**Comment by MoOx** [comment]
J'avais tenter de mettre un rythme vertical, mais jvais virer tout ça, ça fait plus chier qu'autre chose. Merci de le souligner :)

**Comment by kud** [comment]
:D
