### ISSUE TITLE
Post: Introduction à cssnext - translate missing bits of content in EN and ES

### ISSUE THREAD

**Issue by Macxim** [putaindecode/putaindecode.io#433]
See https://github.com/putaindecode/putaindecode.fr/pull/428#issuecomment-107736184

> Quand ce sera lancé, je créerai une issue pour ne pas oublier les traductions manquantes des derniers ajouts.

**Comment by MoOx** [comment]
@Macxim relevant now :)

**Comment by Macxim** [comment]
On it today.

**Comment by bloodyowl** [comment]
j'crois qu'on va abandonner ce post @MoOx haha
