### ISSUE TITLE
Faire un moteur de recherches pour les articles

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.io#435]

**Comment by bloodyowl** [comment]
avec du statique ça va pas être évident

**Comment by MoOx** [comment]
Trop simple. On fait une page avec tous les posts cachés (meta only) en json, puis on fait une recherche dedans (on va trouvé un lib ou ca doit pas etre la mort a faire du indexOf pour commencer) et  on display les PostPreview correspondante.

Même jekyll propose ça. Ex: http://hugogiraudel.com/search/

**Comment by Nyalab** [comment]
je vois 2 solutions

1. avec un moteur de recherche qui se base sur du fichier regénéré à chaque publish (comme notre task contributors)
2. avec une page qui liste tous les posts en `display: none;` et une fonction de filter qui reveal que ceux qui matchent sur les titres ou keywords ou auteurs peut-être

**Comment by MoOx** [comment]
On devra mélanger les 2 @Nyalab, ne serait que pour faciliter le display :)

**Comment by MoOx** [comment]
will be possible with migration to statinamic. See #471

**Comment by MoOx** [comment]
Close in favor of #535
