### ISSUE TITLE
Change fonts

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.io#462]
Je suis de moins en moins fan des fontes du site. Surtout celle du titre.

Je n'ai pas encore de proposition mais j'aimerais si possible que l'on en discute.

@bloodyowl propose `Seravek` qui est mieux à mon sens que ce que l'on a actuellement.

![screen shot 2015-06-16 at 16 00 19](https://cloud.githubusercontent.com/assets/655838/8184932/85d18208-1441-11e5-88d4-a0da7ec9f1e7.png)

**Comment by kud** [comment]
![screen shot 2015-06-16 at 16 00 19](https://cloud.githubusercontent.com/assets/655838/8184932/85d18208-1441-11e5-88d4-a0da7ec9f1e7.png)

**Comment by magsout** [comment]
@kud ton screen est basé sur `Seravek` ?

**Comment by Macxim** [comment]
Oui, c'est celui de @bloodyowl partagé sur Slack.

**Comment by kud** [comment]
Yep @magsout, @Macxim a bien répondu.

Je vais voir de mon côté quelle fonte je peux proposer.

**Comment by MoOx** [comment]
Je propose de virer les fonts de de mettre (--apple-)system-font (fallback Helvetica, Arial).

**Comment by magsout** [comment]
@MoOx y a un site qui utilise cette font pour faire le test ?

**Comment by MoOx** [comment]
Moox.io je crois :)

**Comment by MoOx** [comment]
[Medium recently did this](https://medium.com/@mwichary/system-shock-6b1dc6d6596f#.3io6q9rem).

It seems this is the way for now `font-family: -apple-system, ".SFNSText-Regular", "San Francisco", "Roboto", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif;`

Maybe we should just use a svg for the logo text and use that. Are you ok guys?

**Comment by Nyalab** [comment]
well, why the hell not, it's not like your fonts are awesome right now
