### ISSUE TITLE
Proposition de post: redux avec react

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#482]
petit example simple pour prise en main.

**Comment by madx** [comment]
:+1:

--
François Vaux
http://madx.me/
Le 31 août 2015 16:47, "Maxime Thirouin" <notifications@github.com> a
écrit :

**Comment by magsout** [comment]
🎉

**Comment by Macxim** [comment]
Oui oui oui :+1:

**Comment by bloodyowl** [comment]
:+1: si t'as besoin d'un coup de main

**Comment by lionelB** [comment]
rho cool j'y pensais aussi vu que je voulais l'utiliser
gros +1

**Comment by revolunet** [comment]
yes please

**Comment by MoOx** [comment]
Will do (meme si c'est old)

**Comment by MoOx** [comment]
J'ai la flemme je le ferais pas.
