### ISSUE TITLE
Proposition : Guide de survie du dev web

### ISSUE THREAD

**Issue by revolunet** [putaindecode/putaindecode.io#483]
Si ca vous semble utile, je peux préparer une traduction de ce post : http://blog.revolunet.com/blog/2015/09/04/the-web-developer-survival-guide/

Comments welcome sur le contenu aussi anyway :)

**Comment by MoOx** [comment]
J'ai survolé, ça me parait une bonne idée 👍🏻

**Comment by kud** [comment]
On attend @revolunet  :p

**Comment by drazik** [comment]
Owi !

**Comment by revolunet** [comment]
oops, c un peu outdated now :/
