### ISSUE TITLE
Proposition de post: Why is CLI global usage "not recommended"? (fr+en)

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#490]
Following https://github.com/cssnext/cssnext/issues/150

**Comment by Macxim** [comment]
:+1: Yes please :)

**Comment by magsout** [comment]
:+1:

**Comment by lionelB** [comment]
:+1: aussi

**Comment by kud** [comment]
Interesting but should have a section where you define why some apps should still be in -g. Like `imagemin` or `trash`.

**Comment by MoOx** [comment]
Want to work on this.

**Comment by MoOx** [comment]
Closed by #762
