### ISSUE TITLE
Add a way to "pay" post authors

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#491]
Since this website will never have ads (because ads sucks), what about things like tipee, paypal "pay me a beer" or something like that? Related: https://ploum.net/ce-blog-est-payant/

Obviously, money for one post will be to post author.

Feel free to bring more idea on the table.

**Comment by bloodyowl** [comment]
good idea

**Comment by magsout** [comment]
yes why not.

**Comment by madx** [comment]
Totally!

**Comment by Nyalab** [comment]
agree

**Comment by Macxim** [comment]
:+1: Good idea :)

**Comment by bloodyowl** [comment]
we'll consider this if and when we'll make money

**Comment by MoOx** [comment]
We could authorize some "tricks" to put some links for authors like http://paypal.me/MoOx/2
For eg in author json file a "payMeABeer" link?
