### ISSUE TITLE
Add a "shop" page

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#492]
Following this https://github.com/putaindecode/organisation/issues/30.
I just bough a t-shirt (the last mentionned in this thread), I will tell (and show) you own it looks.
We could imagine mugs and things like that.

Benefit might be used for servers (we don't have yet). We could imagine an association to grab the money.

**Comment by brandonsueur** [comment]
Alors, ça arrive quand ?

**Comment by MoOx** [comment]
Quand on aura fini le redesign. Un jour peut être :)

**Comment by bloodyowl** [comment]
je m'occupe des design cette semaine
