### ISSUE TITLE
Add back custom 404

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#497]
https://github.com/putaindecode/putaindecode.fr/pull/495#issuecomment-153080020

(This issue will make more sense when #495 will be merged :D)

**Comment by kud** [comment]
I've got this as proposal: http://kud.io/demo/gif-homepage/ We could add a text in the middle.

**Comment by MoOx** [comment]
That's not the purpose of this issue :)

**Comment by kud** [comment]
It's not because that it's not the purpose of the issue that you can talk about it.

**Comment by MoOx** [comment]
I think if we want to provide a good UX, we should way for the search engine and deliver a list of post that match some words in the url.

**Comment by kud** [comment]
I agree.

**Comment by MoOx** [comment]
statinamic 0.8 will fix that.
