### ISSUE TITLE
Add a "news" section?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#515]
That can be cool to tell people about the website/org evolution.
Don't you think?

**Comment by magsout** [comment]
I am not against. But I wonder if we will have enough news to have a REAL news section

**Comment by MoOx** [comment]
Not a lot, and probably just little posts.
That can be handy to explain some changes for the website/org etc:
Examples:
- s/slack/discord
- engine update (so people might be careful and report bug, learn a new tool etc)
- organisation update (owners rules, new guidlines etc
- post about the new (incoming) shop section...

**Comment by Macxim** [comment]
Alright, why not :) 
As long as posts remain the main section.

**Comment by magsout** [comment]
And myabe use this section to post short news about new from other websites ?

**Comment by MoOx** [comment]
why not. Or maybe a "links" section for that. With link to good post + some thoughts about it (like http://daringfireball.net often does)

**Comment by Uhsac** [comment]
Agree with @magsout idea !

**Comment by kud** [comment]
It could be great indeed to have some short news. Like @magsout said.

**Comment by bloodyowl** [comment]
.+
