### ISSUE TITLE
Should we drop the "/projects" page?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#520]
It's always outdated imo and pretty useless.

**Comment by MoOx** [comment]
It's always outdated imo and pretty useless.

**Comment by Nyalab** [comment]
dont know why this has not been closed via your commit, but i agree, this page is useless

**Comment by MoOx** [comment]
Commit is not in master yet, that's why.

**Comment by magsout** [comment]
drop that page

**Comment by Macxim** [comment]
Agree.

**Comment by madx** [comment]
If they are not supported by p! anymore, does it make sense if we get them back to their respective owners?

**Comment by MoOx** [comment]
The real issue here was just an outdated page.
I think the fact that a project is under the p! org means it's supported.
That said if you want to get back a project were no one is involved except you, just ask directly for that :)
