### ISSUE TITLE
Normalize some posts tags

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#523]
- reactjs: react
- iojs: nodejs
- nodejs: node ?

**Comment by kud** [comment]
Yep.

**Comment by MoOx** [comment]
On a du react, reactjs, javascript, JavaScript, js... Je peux faire un petit cleanup 

Je partirais sur:
- case d'origine
- tout ce qui n'est a-zA-Z: -
- pas de - qui se suive.

Du coup ça donnerais des tags du genre: React, JavaScript, Node-js, style-inline
