### ISSUE TITLE
Drop google analytics?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#525]
For privacy reasons?

Maybe we can use http://keen.io/ instead ?

**Comment by Nyalab** [comment]
don't really care about that, do whatever you guys want

**Comment by magsout** [comment]
We need a cookies Popin, because of analytics .. 

I don't know keen.io, so hard to make my decision.

**Comment by MoOx** [comment]
It's just that google is evil, and keen (that as been recommended to me on twitter a few weeks ago) seems a nice alternative.
For the poop(in), I think I heard that the law is going to change again, but I might be saying pure shit.
Another solution is to completely remove any sort of analytics, but that's kind of brutal...

**Comment by magsout** [comment]
>It's just that google is evil, and keen (that as been recommended to me on twitter a few weeks ago) seems a nice alternative.

Ok ok. So why not.  We can make some test 

> Another solution is to completely remove any sort of analytics, but that's kind of brutal...

yeah, it's cool to have some information about visitors. So no ?

**Comment by MoOx** [comment]
Anyone opposed to this? Any thoughts?

**Comment by MoOx** [comment]
Btw, I just saw that analytics are broken since we merged statinamic... Weird cause I don't have this issue on other projects using it. Will double check.

**Comment by MoOx** [comment]
FYI, analytics should work now, the UA wasn't set :D

**Comment by Macxim** [comment]
Any thoughts on http://piwik.org/?

**Comment by MoOx** [comment]
Require a server. And their hosted offer is expensive.
