### ISSUE TITLE
Proposition de post : le favicon

### ISSUE THREAD

**Issue by phbernard** [putaindecode/putaindecode.io#526]
Oui, oh, je sais, le favicon est ce petit truc qu'on fait tout à la fin du projet, ou quand on a 5 minutes avant de partir manger alors que les collègues ont du mal à s'arracher de leur clavier. Pourtant, ça n'est pas si simple.

Déjà, il faut faire vite. Passer des heures sur l'UI, un beau build file ou l'intégration continue, ok. Mais le favicon, franchement... Du coup ça laisse peu de temps pour bien faire les choses. Alors que c'est loin d'être simple. La taille max d'une touch icon ? (indice: le premier résultat de Google pour "apple touch icon size" est complètement dépassé) Pour Android, ça se passe comment ? Vous avez vu les pinned tabs de Safari, cool hein ?

D'accord, il y a des générateurs. Dont un bon, dont je suis l'auteur par le plus grand des hasards. Mais ça ne fait pas tout. Télécharger à la main un framework JavaScript et le coller tel quel dans son projet, ça ne se fait plus trop n'est-ce pas ? Pourtant c'est ce qu'on fait avec les fichiers et le code du favicon. Pas top.

Ma proposition : un article qui explique les tenants et aboutissants du favicon de nos jours (sans entrer dans les détails, il s'agit de faire comprendre la problématique) et explique comment s'en dépatouiller vite et bien avec Gulp.

Disclaimer : donc apparemment je suis l'auteur d'un <a href="https://realfavicongenerator.net/">générateur de favicon</a>, et oui, il propose une passerelle vers Gulp. Du coup cet article ressemble à une bonne grosse PR. Je le propose car il me semble que le sujet est intéressant et en ligne avec P***** (quelle grossièreté !) de code, voilà, vous savez tout.

**Comment by phbernard** [comment]
*PR = Press Release, rien à voir avec GH pour le coup.

**Comment by magsout** [comment]
Déjà bravo @phbernard pour ton outils en ligne, que j’utilise à chaque projet ;)

Ensuite, pour m'être bien pris la tête à comprendre toutes les meta qu'il fallait, savoir les bonnes résolution, les extensions. De plus maintenant le SVG est compatible sur certains navigateurs. Je trouve que cet article est une bonne idée (surtout si il y a eu des nouveautés depuis mes dernières recherches)

Pour moi :+1:

**Comment by Uhsac** [comment]
J'aimerais en savoir plus ! Go go :+1:

**Comment by Macxim** [comment]
:+1:

**Comment by drazik** [comment]
J'aimerais aussi en savoir plus sur ce sujet. Par l'auteur du générateur qu'on utilise (je pense) tous, que demander de mieux :)

**Comment by MoOx** [comment]
@phbernard bonne idée de post, on doit tous bien avouer qu'on sait jamais ce qu'il faut ajouter à nos pages...
Je viens de faire un test avec l'outil, bonne expérience :)

Cela étant dit j'ai quelques questions:
- vu que y'a un version grunt et gulp, pourquoi ne pas simplement faire une version node ? Voir un outil CLI ? Là ça serait le top du top (je dis ça car la plupart d'entre nous on utilise plus gulp (et oui... webpack ^^)
- tous les icones sont-ils _vraiment_ (grosse question) nécessaire? Ne peut-on pas se limiter à 2/3 voir?

Je vois bien pour le coup 2 posts:
- un sur le topo favicon et apple-touch machin truc, un post à maintenir dans le temps pour éviter que ça périme quand ça sera nécessaire, qui incluera une référence à ton outil sans trop s'attarder dessus
- un petit post sur l'utilisation de ton outil via gulp

**Comment by phbernard** [comment]
Merci pour ces retours !

Les plugins Grunt et Gulp s'appuient sur un unique module (https://www.npmjs.com/package/rfg-api), donc dans le principe, on peut faire du pur Node. Pas de CLI pour le moment, j'attends de voir comment sont accuillis les plugins.

Non, toutes les icônes ne sont pas nécessaires. Les premières visées : la palanquée de touch icon. J'ai encore des essais à faire (notamment le rendu d'icônes façon pixel art, qui nécessitent un algo type nearest neighbour pour être retaillées correctement... j'ai peur qu'iOS n'ait pas tous ces principes). Néanmoins il faut plus de 2 ou 3 icônes pour faire le job, d'autant que beaucoup sont "gratuites", comme les icônes pour Android Chrome qui sont déclarées dans un manifeste séparé, donc sans alourdir le HTML.

J'étais parti pour parler méthodo et outil, mais pourquoi ne pas parler des icônes elles-même en effet ? J'ai écrit un article de ce style pour CSSTricks, mais c'était il y a un peu plus d'un an, donc il y a matière développer.

Chaque chose en son temps : je commence par le premier post, je vous soumets ça et on avise.

**Comment by MoOx** [comment]
Closed by #532

**Comment by phbernard** [comment]
Merci @MoOx !
