### ISSUE TITLE
Improve "top contributors" ranking

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#527]
Following this PR https://github.com/putaindecode/putaindecode.fr/pull/516

Initial idea:

For now it's a simple and stupid ordering by number of commits.
Since a commit can be a typo or a fucking entire post, we should take that into account.
I was thinking about something like this:
- a comment in an issue on this repo: 1 point
- a commit in the repo: 10 points
- a review: 20 points
- a post: 100 points.

**Comment by Nyalab** [comment]
this is not blocking for #628, but for further improvement:

after watching the github api docs and considering the issue i think something like:
- creates or comments or closes on an issue: 2pt
- comments only a :+1: or only emoji on a issue, PR: 1pt
- comments on a PR: 5pts
- creates or closes a PR: 100pts (only once if this is the same person, that means he has created a post)
- commits on the repo: 20pts
- becoming a collaborator on the repo: 50pts (it is a small bonus for the first time :smile: to bring people in)
- become a member of putaindecode org: 10pts

**Comment by MoOx** [comment]
Something simple to start:

- 1 comment: 1 point
- 1 commit: 10 point
- 1 review: 20 points
- 1 trad: 50 point
- 1 post: 100 point

The hardest part is to count everything related to comments as we discussed on Discord.
A fun thing can be to have a "timeline" page where we display last 200 activities (should not take long since with the algo, we will already have all actions, this will just be a thing to display).

Will try to work on that soon.
