### ISSUE TITLE
Proposition de post : [iOS] séparer ses Storyboard  (a.k.a diviser pour mieux régner)

### ISSUE THREAD

**Issue by leoderbois** [putaindecode/putaindecode.io#528]
Yop, Je voudrais proposer un post sur du Dev iOS. Pour commencer avec un truc simple, j'aborde les Storyboards, qui parlent à tous dev iOS ( ce sont les fichiers d'interface).

Voici les grandes étapes de mon post : 
- qu'est ce qu'un storyboard (rappel)
- avantages a en avoir plusieurs (par default Xcode n'en propose qu'un pour tout faire)
- comment on fait (pour en avoir plusieurs et pour interagir entre eux)

C'est un sujet pour débutant qui cherche a aller plus loin. Mais d'après vos conseils il vaut mieux ça que le sujet hardcore pour commencer. 

Si vous voulez un aperçu, voici mon brouillon (je travail encore dessus) : 
https://www.dropbox.com/s/505wj4im002j9e8/index.md?dl=0

Hésitez pas à corriger/conseiller etc. Je me doute que ça parle pas forcément à grand monde ici le dev iOS, mais hésitez pas à dire ce que vous en pensez !

**Comment by MoOx** [comment]
Hello @leoderbois.

C'est vraiment cool d'avoir de nouvelles choses sur notre site.

Quelques questions / remarques:
- Pourrait on imaginer un premier petit post d'intro sur le dev iOS, et comment commencer un hello world? (je ne connais encore rien au dev ios et je t'avoue que ton article m'effrait un peu du fait que je ne pige rien ^^)
- Je verrais bien des articles qui n'ont pas de context temporel, dans ce sens les tournures tel que la première phrase qui indique que c'est le premier post sur le dev IOS pourrait être évité (dans le fond que ce soit le premier ou le 10e post, on s'en fou non?)
- Essaye d'éviter les tournures à la première personne sauf pour les prises de positions (on avait eu une discussion sur ce sujet https://github.com/putaindecode/organisation/issues/41 mais pour l'instant rien n'est fixé "officielement")

Ensuite si tu veux itérer via une PR, pas de soucis prends juste ça en compte https://github.com/putaindecode/putaindecode.fr/blob/master/CONTRIBUTING.md#soumettre-un-post
Note: plutôt que /posts/, on est en train de i18nisé le site (cf #524), donc met ton post dans `content/fr/articles/ios/`.

Tu pourrais d'ailleurs faire un post d'intro (ou genre un index) ici `content/fr/articles/ios/ ` puis placer ton post sur les storyboards `content/fr/articles/ios/storyboards/` et y faire référence dans le post d'intro ios.

J'en demande beaucoup à première vu, mais ça me parait un must have sur le long terme. Dans l'idée j'aimerais bien que putaindecode deviennent une sorte de wiki des bonnes pratiques du code (on a dans l'idée de maintenir les posts ou de déprécier carrément si besoin).

Libre à toi de venir discuter de tout ça avec nous sur Discord.
Ca serait vraiment top d'avoir des posts sur iOS (moi j'aimerais bien m'y mettre - via react-native pour faire aussi du dev android).

🤘🏼

**Comment by leoderbois** [comment]
Salut @MoOx,

- Je veux bien faire un post "hello world", mais je l'écrirai après avoir fini celui ci, je préfère finir ce que commence. Et tant qu'a faire je le ferais surement en Swift, parce que le Hello World Objective C existe surement sur des milliers de site.

- Je rectifie mon article en ce qui concerne la notion temporelle et la première personne. 

- Pour le post d'intro et les sous dossiers, ça me va. Mais j'ai vu que le dossier `content/fr/articles` n'existe pas encore, je le créé ? et ça va marcher au niveau de la génération du site ? (je connais pas assez Node pour me permettre de modifier des choses pour que ça marche ^^)

**Comment by MoOx** [comment]
- Aucun soucis pour un hello world en swift !
- Nickel
- fait comme tu le sens, tu n'as qu'à laisser dans /posts si ca marche pas dans content/fr/. En fait si ca commence pas par /posts tu verras pas ton post dans le listing du site (pour le moment), donc faudrait que tu tapes sur l'url à la main (genre `http://0.0.0.0:3000/fr/articles/ton-slug`) une fois que le serveur de dev est démarré.

**Comment by MoOx** [comment]
Pour info la nouvelle arbo est en place sur la master.

**Comment by MoOx** [comment]
Closed by #545
