### ISSUE TITLE
Github pages respond with a HTTP 302

### ISSUE THREAD

**Issue by Uhsac** [putaindecode/putaindecode.io#533]
This don't happen all the time for normal user, but when it happen this slow the loading.

But the biggest problem is for search engine bot, if they see to much 302 they will stop the crawl sooner and that's bad for referencing

Solution seem to be some change on DNS server

Some links about this:
- http://stackoverflow.com/questions/20885695/why-is-my-github-hosted-site-responding-with-http-302-instead-of-200
- http://subosito.com/github-hosted-redirect/

![image](https://cloud.githubusercontent.com/assets/6172122/11150596/0bbcc46a-8a29-11e5-90a9-ee9b91efecbe.png)

**Comment by MoOx** [comment]
I just take a quick look and our current domain provider (gandi.net) doesn't support ALIAS entries.
I have no idea how we can fix this :(

**Comment by MoOx** [comment]
Hum the stackoverflow issue explain another trick, I will try that.

**Comment by MoOx** [comment]
I am trying things with my personnal website, I will wait for dns propagation and see what happens :)
If things looks good, I will be able to fix that issue.

**Comment by Uhsac** [comment]
Nice !

**Comment by MoOx** [comment]
Ok my test was stupid since this can only work with a subdomain. We don't use any.
So we are stuck with this solution until we find a free DNS provider that can offers ALIAS.
Anyway, 302 seems to be a protection related to the DoS protection system github is using.
Not a big deal imo.

**Comment by Uhsac** [comment]
Ok, you can test [this](https://support.google.com/webmasters/answer/6066468?hl=en) to see if google crawl putaindecode correctly (I can't do as it's not my website)

**Comment by MoOx** [comment]
We got an issue with fg og #551
