### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#535]
Because now we can.

**Comment by Nyalab** [comment]
:+1:, will do when i have time for it, if no one has done it before

**Comment by MoOx** [comment]
That component can be interesting https://github.com/moroshko/react-autosuggest

**Comment by lionelB** [comment]
what about using a something algolia ?

**Comment by leoderbois** [comment]
:+1:

**Comment by MoOx** [comment]
I would like to add algolia!

**Comment by bloodyowl** [comment]
we should do this with the website redesign then.

**Comment by MoOx** [comment]
I will obviously work on the engine part in phenomic whenever it's relevant :D

**Comment by MoOx** [comment]
Sure

**Comment by MoOx** [comment]
done
