### ISSUE TITLE
missing  module 'svgo' in the install file

### ISSUE THREAD

**Issue by leoderbois** [putaindecode/putaindecode.io#537]
Hey,

After a new install of my computer and new `clone` I run `npm install` and `npm start` and I get this error during the start : 

```
ERROR in Cannot find module 'svgo'
 @ ./web_modules/Header/index.js 97:21-60
```

After a 
` npm install svgo`

all looks good. So it look like it missing `svgo` from the npm install file. 

good day

**Comment by MoOx** [comment]
Are you using npm@3?
I guess you are right?

**Comment by leoderbois** [comment]
hi @MoOx,

I use npm 3.3.9.
