### ISSUE TITLE
Choose a font for "Putain de code !" identity

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#541]
Following the change of font (#539 ), we might want to choose a specific typo for our title, in order to have our own identity.
That will be handy, especially for the incoming products (t-shirts etc) in the shop (see #492)
"Putain de code !" with Avenir looks nice. Does any of you have a better idea or want to submit anything?

**Comment by MoOx** [comment]
Bump. @Nyalab is asking for normalized t-shirts. The shop is almost ready but I want to normalize the logo before opening it.

**Comment by MoOx** [comment]
This is blocking the Shop #492

**Comment by Nyalab** [comment]
why not playing the "developer game" fully and chose a developer font for the website? It could be pretty and original.
Something typical like Inconsolata, Menlo, Fira Code, Consolas, ... It could be a dumb idea, what do you think?

**Comment by lionelB** [comment]
I like Avenir in Medium/Book, readability is good

**Comment by Nyalab** [comment]
@lionelB we are talking about the "Putain de code !" logo font, not the content one.

**Comment by lionelB** [comment]
yep, that's what I said

**Comment by bloodyowl** [comment]
I'd remain with Avenir, San Francisco could also be nice

**Comment by ooflorent** [comment]
Use `system-font` polyfill. Web fonts are a burden on low bandwidth connections...

**Comment by MoOx** [comment]
No font will be used. This will become an svg logo (a path).

**Comment by lionelB** [comment]
+1 for the svg

**Comment by MoOx** [comment]
Bump. Should we finish the shop with the current logo?

**Comment by bloodyowl** [comment]
New identity uses Colfax, more on that later
