### ISSUE TITLE
Update post about autoprefixer

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#544]
Commands and snippets are not accurate anymore http://putaindecode.io/fr/articles/css/autoprefixer/mise-en-place/#comment-2374338657

**Comment by bloodyowl** [comment]
does it still matter?

**Comment by MoOx** [comment]
balek
We should auto display a message on old post to say "it might be out of date" or something like that imo. Because many posts are affected by this syndrom
