### ISSUE TITLE
Change default rules to merge PR

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#549]
Currently the rule was: 3 OK responses > can merge.
What about something like:

> 3 OK responses without NOK: can merge now
> or can merge if 80% of OK in all feedback in 7 days

**Comment by magsout** [comment]
We need in both case a minimum of day. For your first propal maybe 2 or 3 day...

**Comment by Nyalab** [comment]
i agree with something like @MoOx said, the inactivity on the reviews/answers is killing the motivation of the authors

**Comment by magsout** [comment]
>i agree with something like @MoOx said, the inactivity on the reviews/answers is killing the motivation of the authors


:100:

**Comment by bloodyowl** [comment]
I think the current flow is pretty good
