### ISSUE TITLE
Facebook Open Graph Object doesn't work properly

### ISSUE THREAD

**Issue by leoderbois** [putaindecode/putaindecode.io#551]
Hi,

the meta used for Facebook Open Graph (and sharing on Facebook) doesn't work properly for theses articles : 

http://putaindecode.io/fr/articles/js/react/test-unitaires/
http://putaindecode.io/fr/articles/xcode/storyboards/diviser/ (FR && EN)
http://putaindecode.io/en/articles/css/preprocessors/cssnext/

You can validate Open Graph meta here : https://developers.facebook.com/tools/debug/og/object/

**Comment by MoOx** [comment]
Ok this is related to #533 (302 redirect...). Fuck.

**Comment by bloodyowl** [comment]
Closing if it only concerns 3 old posts

**Comment by MoOx** [comment]
No it's a github pages issue. So it concern all posts. But we should use netfliy so... Will be fixed
