### ISSUE TITLE
Give write access to all authors ?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#552]
This is an idea to encourage more commits.
Comments are welcome.

**Comment by Nyalab** [comment]
good idea, but we have to protect the `master` branch, so PRs are becoming mandatory for most of people

**Comment by kud** [comment]
I agree with @Nyalab.

**Comment by MoOx** [comment]
How can we protect master?

Can't we just educate people who get write access to not commit in master (except for major issues), and if some failures happen, we might revise the situtation?

**Comment by Nyalab** [comment]
no, we protect the master branch, this is a good habit.
![](http://cl.ly/image/3k2O041U3G3v/Screen%20Shot%202015-12-01%20at%2010.55.09.png)

**Comment by bloodyowl** [comment]
good idea

**Comment by magsout** [comment]
yes, good idea. :+1:

**Comment by MoOx** [comment]
Protect master just prevent deletion and force push.
I will add write access to the "Authors" team.

**Comment by lionelB** [comment]
ok to give access to all authors. it's a nice move

**Comment by kud** [comment]
Perfect @Nyalab

**Comment by MoOx** [comment]
Before giving write access, I will write a doc about what you need to know when you are in the "Authors" team.

**Comment by Macxim** [comment]
Excellent idea! :+1: For @Nyalab's suggestion 🎉

**Comment by Nyalab** [comment]
indeed, i thought protecting branches instantly forbade (yes it exists) all pushing to this branch

but i still don't like that all authors have access to merge, and commit to master

**Comment by MoOx** [comment]
You don't trust contributors ? Come on...

**Comment by MoOx** [comment]
One day someone gave me write acces to reworkcss organization after I make my first PR. You know what happened next.

**Comment by Nyalab** [comment]
nope, git knowledge is not correlated with writing skills

**Comment by MoOx** [comment]
Note: I already made some shit on a master, but I fixed it pretty quickly. That's how you learn the best.
FYI, a broken putaindecode master branch (or even putaindecode.io) is not a big deal imo.

**Comment by Nyalab** [comment]
2 points of view, let's hear what other have to say

**Comment by madx** [comment]
Suckless guys went even further and made the ENTIRE website world-writable http://suckless.org/wiki

I think they never had any problems with it

**Comment by kud** [comment]
I don't see what's the problem with locking the master. I could see one by uncloking it.

**Comment by MoOx** [comment]
I sometimes commit to master when it's for small fixes or typo. Is this a problem?

**Comment by kud** [comment]
In any case, PRs are/should be mandatory. So locking or not doesn't change anything but should be "on" because "we never know".

**Comment by lionelB** [comment]
> but should be "on" because "we never know".

I definitly prefer to trust and bet on people

**Comment by MoOx** [comment]
@kud Again, master cannot be "locked", it can just **protected** to force push and deletion. Again, this is already done and is not the point of the issue.
Anyway, the majority of people seems to be agree of the fact that giving write access is a good thing, so we will definitively do it and see what happen.

**Comment by Nyalab** [comment]
clear proof that democracy is work weak people :trollface:

**Comment by lionelB** [comment]
@Nyalab you should stop google translate ihmo :trollface:

**Comment by Nyalab** [comment]
finally, i agree on this one @MoOx should i do it? so we just add to the authors group people that wrote an article for us? should we rename the authors group to contributors?

**Comment by MoOx** [comment]
Not sure to ALL contributors. Fixing a typo should not grant write access to the repo. Writing a post should. Any thoughts?

**Comment by Nyalab** [comment]
each people with a `.json` in our repo should be in that group, i think it is simple enough to show the dedication, but not too much

do you agree?

moreover, i don't like "authors" as a group name, "contributor", "putaindecoder" ?

**Comment by MoOx** [comment]
Only post authors are in the "Authors" group (which make sense).

**Comment by MoOx** [comment]
This is it.

@putaindecode/authors you now have write access to all repositories !

We will clearly document workflow asap. Please make issue PR before making changes (anyway, only owners can push directly to master).
