### ISSUE TITLE
🎄 Advent calendar ES6/2015

### ISSUE THREAD

**Issue by bloodyowl** [putaindecode/putaindecode.io#553]
1. let/const http://putaindecode.io/fr/articles/js/es2015/const-let-var/ 
- destructuring http://putaindecode.io/fr/articles/js/es2015/destructuring/
- default params http://putaindecode.io/fr/articles/js/es2015/defaults/
- Object.assign http://putaindecode.io/fr/articles/js/es2015/object-assign/
- classes http://putaindecode.io/fr/articles/js/es2015/classes/
- Promises http://putaindecode.io/fr/articles/js/es2015/promises/
- template strings http://putaindecode.io/fr/articles/js/es2015/template-strings/
- enhanced object literals http://putaindecode.io/fr/articles/js/es2015/object-literals/
- iterators http://putaindecode.io/fr/articles/js/es2015/iterators/
- generators http://putaindecode.io/fr/articles/js/es2015/generators/
- Maps/WeakMaps http://putaindecode.io/fr/articles/js/es2015/maps-weakmaps/
- rest/spread http://putaindecode.io/fr/articles/js/es2015/rest-spread/
- new array methods http://putaindecode.io/fr/articles/js/es2015/array-methods-addition/
- async/await http://putaindecode.io/fr/articles/js/es2016/async-await/
- arrow-functions http://putaindecode.io/fr/articles/js/es2015/arrow-functions/
- for..of http://putaindecode.io/fr/articles/js/es2015/for-of/
- Symbols http://putaindecode.io/fr/articles/js/es2015/symbols/
- Proxy http://putaindecode.io/fr/articles/js/es2015/proxy/

--- Not done
- Sets/WeakSets @bloodyowl
- modules @bloodyowl
- decorators @jbleuzen
- octal & binary literals
- Reflect
- babel @MoOx

**Comment by kud** [comment]
![1444938983_like](https://cloud.githubusercontent.com/assets/655838/11503355/6aaf6584-9840-11e5-82fd-18d4fde079c6.png)

**Comment by MoOx** [comment]
let / const in one day imo, let is pretty useless.

**Comment by lionelB** [comment]
I disagree, let is not pretty useless, its not just like var cf https://youtu.be/uL9uAAzkFmI?t=1661

**Comment by MoOx** [comment]
poke @naholyr

**Comment by MoOx** [comment]
I think one attribution at a time is cool. Let's prepare some posts :)

**Comment by MoOx** [comment]
/fr/articles/js/es2015/index.md for the listing +  /fr/articles/js/es2015/*.md for all tiny posts.
We should deliver french post first and we can work on translation together.

**Comment by MoOx** [comment]
es201* btw ?

**Comment by MoOx** [comment]
Note: that might helps a little :) http://babeljs.io/docs/learn-es2015/

**Comment by Nyalab** [comment]
es6, fuck translations for now

**Comment by jbleuzen** [comment]
Nice ! 
Would love to write something for template strings :)

**Comment by Uhsac** [comment]
I can try to write something too.

es2015 :D

**Comment by lionelB** [comment]
> Nice !
> Would love to write something for template strings :)

done @jbleuzen

**Comment by naholyr** [comment]
Volunteer ;) I'll take a late one (or many), so I get time to prepare as I never contributed before, any of those, your choice:

* default params
* async/await
* Object.assign
* object spread

If you can't choose, I'll take async/await 'cause I love it and there are tricks (beware series vs concurrent).

**Comment by magsout** [comment]
@naholyr assigned for ` async/await`;)

**Comment by MoOx** [comment]
@Nyalab I update the desc since your post is out, so feel free to take another one ;)
I will try to take care of translations when an author don't have the time for it.

**Comment by bloodyowl** [comment]
je me propose pour 

- Maps/WeakMaps
- Sets/WeakSets
- modules

**Comment by MoOx** [comment]
Let's make things simple, @naholyr and @bloodyowl I assigned you the post you asked for.
If someone wants to handle it before you did anything, let's just discuss about it here.

**Comment by naholyr** [comment]
I'd rather delay async/await *after* generators (makes it simpler to explain how a function can "idle"), but if not possible it's OK. Maybe delay it to 10+ so we can have a few more days to check if we can get the article about generators or not.

**Comment by MoOx** [comment]
The order above is not relevant, I just moved assigned post at the top. So we will take at they come :)

**Comment by magsout** [comment]
I take classes

**Comment by Uhsac** [comment]
I'm on it but it's only a small draft for now, I think 4 december is too soon for me

**Comment by MoOx** [comment]
The order of the list is not the date :)
For now we have enough PR to not be in a hurry !

**Comment by ffesseler** [comment]
Cool list. There should be a subject dedicated to the iteration protocols too IMO as it's used by many of the other subjects listed above

**Comment by MoOx** [comment]
Thre is still one spot @ffesseler, do you want to take care of it ?

**Comment by ffesseler** [comment]
Deal :)

**Comment by MoOx** [comment]
Assigned :)

**Comment by MoOx** [comment]
FYI here is a PR for the calendar view https://github.com/putaindecode/putaindecode.io/pull/562

**Comment by zoontek** [comment]
Je veux bien faire rest & spread, for of ou Symbols

**Comment by davidbgk** [comment]
Typo : `Si vous voulez aideR, c'est par ici` :D

**Comment by MoOx** [comment]
We have 2 posts in the pipe, so who can deliver one post for:
- sunday 6
- monday 7
- thuesday 8

**Comment by MoOx** [comment]
@zoontek assigned for rest & spread

**Comment by ffesseler** [comment]
I'll probably write about for .. of in the iteration protocols article as they are directly related. Not sure they should be separated.

**Comment by MoOx** [comment]
@ffesseler make sense.

**Comment by naholyr** [comment]
Started working on object spread and… there is literally nothing to say after Object.assign :/ I see two options:

* Repeating the same article :P
* Writing three lines to explain it's basically the same thing
* Let the article on rest/spread include it, and add another topic, like:
  * Enhancement in RegEx
  * New String methods (my favorite, simple and useful)
  * Typed arrays

What do you think? Anyway, you can unassign me on this one while you decide, and assign me on generators. As it's pretty close to async/await I think it's logical to start with this one ;)

**Comment by MoOx** [comment]
Ok so I guess @zoontek will talk about object spread (and refer to Object.assign post).
@naholyr assigned for generators

**Comment by MoOx** [comment]
@ffesseler I merged for of and iterators protocol and assigned this to you.

Who will be able to deliver a post for sunday and the following days?

**Comment by MoOx** [comment]
I am going to translate and publish Object.assign post since post about classes is not ready yet.

**Comment by lionelB** [comment]
I've planed to do so since I should have some spare time in train

**Comment by MoOx** [comment]
Cool thanks !
Someone for monday? thuesday?

**Comment by jbleuzen** [comment]
I think I can be ready for monday.

**Comment by bloodyowl** [comment]
I'll have a few posts ready during the week-end

**Comment by MoOx** [comment]
There is no more PR atm, so we will need more posts. @bloodyowl, feel free to push you draft(s) so we can improve it together :)

**Comment by ffesseler** [comment]
I should be able to make a PR before tomorrow evening

**Comment by MoOx** [comment]
@ffesseler do you want to handle another post about for..of ?

I am going to handle fat-arrow for friday (since we have post for tomorrow and the day after).
Is anyone going to prepare some posts for saturday/sunday? @bloodyowl maybe?

Note: I did not write any post yet because I handle of the translations in english :)

**Comment by lionelB** [comment]
> Note: I did not write any post yet because I handle of the translations in english :)

Thx!

Je vais préparer les nouvelles méthodes de prototype

**Comment by MoOx** [comment]
No more PR are awaiting for this weekend, I will try to handle fat arrow post but not sure I will be able to take the time for it.
New PR are welcome :)

**Comment by jbleuzen** [comment]
Can someone tell me what is "new prototype methods" ?
Does it means new String and Array methods available with ES6 (for example) ? Or is it something related with `__proto__`?
I could write and learn something on these subjects :)

**Comment by MoOx** [comment]
I think @lionelB just said he would handle this post... :/

**Comment by lionelB** [comment]
@jbleuzen  What I've in mind was String / Array / Object new method available with es6

**Comment by jbleuzen** [comment]
Oh f*** didn't see that... It was just 2 posts before. :/

**Comment by lionelB** [comment]
No pb :)  Decorators are yours (I've updated the list accordingly)

**Comment by MoOx** [comment]
@jbleuzen from what I understand, decorators are not in ES6 and it seems they won't be in ES7 so, be aware of that ;)

**Comment by jbleuzen** [comment]
@MoOx Yes I saw Decorators are mentionned for ES7... Is it still in scope then ?

**Comment by MoOx** [comment]
Not sure but I am not the boss here ^^

**Comment by MoOx** [comment]
I think we should focus on ES6 first, and if we run out of subjects, we can handle ES6+ ?

**Comment by naholyr** [comment]
I'll try to write async/await by the week-end but I really can't guarantee
anything earlier than monday night

**Comment by MoOx** [comment]
Later are better than never ^^, don't worry, you already wrote a lot @naholyr <3

**Comment by MoOx** [comment]
We are only 2 day late, I was thinking it would have been worst :)
Thanks for everyone involved in this !

**Comment by Freezystem** [comment]
J'veux bien essayer de vous faire un draft pour le `for..of`, j'ai vu qu'il n'y avait pas de preneur encore. J'commence en français et j'ferai éventuellement la traduction en anglais dans un second temps si ça vous convient.

**Comment by DavidBruant** [comment]
Les proxy ! Les proxy !
Je peux le faire si personne ne s'y met, mais je ne peux l'écrire que la semaine prochaine. Lundi ?
Reflect peut rentrer dans le même mouvement vu que c'est très lié.

**Comment by divarvel** [comment]
Je peux faire un truc sur les symboles au besoin.

**Comment by MoOx** [comment]
@DavidBruant assigned on proxy !
@divarvel assigned on symbols !

No need to hurry, better late than never :)

Thanks.

**Comment by MoOx** [comment]
@Freezystem assigned on for..of

**Comment by Freezystem** [comment]
Article is on the way ! I'll try to finish asap and send the PR right after. Do you want me to translate it to english before or after you review the article ?

**Comment by MoOx** [comment]
As you want.

**Comment by Freezystem** [comment]
m'key I'll decide when I'll be done with the french one.

**Comment by DavidBruant** [comment]
Juste pour tenir au courant, j'ai commencé le draft. Pas sûr que j'aurais fini ce soir. Demain me parait plus plausible. L'article sera un peu long (les proxies, c'est un peu balourd, mon style d'écriture peut-être un peu aussi).

**Comment by MoOx** [comment]
@DavidBruant cool !

**Comment by MoOx** [comment]
Thanks for all the contributions.
Only 6 items left. We can make it.
@bloodyowl @jbleuzen any update for your posts?
Anyone wants to handle another post?

I will try to work on translations (there is some to be done).

**Comment by MoOx** [comment]
I will work on post about babel (we don't have any yet) for the 24th.

**Comment by MoOx** [comment]
I will try to handle some missing translations, but I don't think we will succeed to get 6 posts...
Should we consider it's done and accept the unfinished calendar?
Maybe we can edit the calendar view to say we won't finish this?

**Comment by jbleuzen** [comment]
Sorry, I had no time to try to write anything about my post. 
And I think that calendar should be closed with a small conclusion… It's hard to last 25 days without some preparation.

**Comment by Nyalab** [comment]
i can take one, but people should do their part, just try to finish the damn thing, @bloodyowl @jbleuzen, are you still good for finishing your posts?

**Comment by MoOx** [comment]
Pressure is unnecessary and doesn't help.
If someone want to write => PR,
if someone doesn't, no big deal. Anyway finishing an advent calendar in january is a joke.
We should just admit (even if we have lot of good post) that it's not finished.
Next time we should prepare ourselves.

**Comment by Nyalab** [comment]
i do not want to put pressure, i'm just asking because their names are next to the post names, i think this would be a good thing to finish what we started (like kylo ren said), else we should not be very proud of it

**Comment by MoOx** [comment]
My 2 cents: we should admit the failure now instead of doing it in a month or two.

**Comment by Nyalab** [comment]
imho it's a kind of disrespect for each author that put work in this project not to finish it, but i would like to have the thoughts of others on it (including non-staff members of course if you want)

**Comment by bloodyowl** [comment]
I'm finishing my two post tonight anyway

**Comment by DavidBruant** [comment]
> imho it's a kind of disrespect for each author that put work in this project not to finish it, but i would like to have the thoughts of others on it (including non-staff members of course if you want)

I don't feel disrespected at all. 18 quality posts is already a good performance for something started literally on Dec 1st. 18 the first time with no preparation is a good sign that next year 25 will be doable if not easy.

**Comment by Freezystem** [comment]
Let say that the idea was great but comes pretty late. Tomorrow will be another day. I'm glad that everything not run as expected cause without that I could not have wrote my article and join this great project. I personally not feel any kind of disrespect as I'm sure everyone has done his best to provide great content, but I'll be a bit disappointed if this calendar stay incomplete as I'm constantly referring to these posts when I have a blank or when I want to clarify my understanding about a new feature.

> Better late than never.

Hope someone will take the time to finish what was started. 
:+1: Great Job everyone by the way.

**Comment by MoOx** [comment]
The joke has gone on long enough, closing.

Reminder: huge thanks to every single contributors. You will gain full write access to this repo really soon, and remember that you can make a PR every time you feel the need if you want to share something :).
