### ISSUE TITLE
Remove "crew" prop from author json files ?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#559]
Because we don't use it.

**Comment by leoderbois** [comment]
:+1:

**Comment by naholyr** [comment]
:+1: I wondered what it was about at first ;)

**Comment by Nyalab** [comment]
i don't agree :-1:

**Comment by MoOx** [comment]
So, what is it for? It's unused atm.

**Comment by Nyalab** [comment]
i know it is not used, but i think the crew should be displayed somewhere even if we promote the most active users

**Comment by kud** [comment]
+1 with @Nyalab

**Comment by MoOx** [comment]
To me, the "crew" is constantly changing: it's just the people who contribute the most. We already talk about this "crew" thing at the beginning, but we can note that the only attempt to show a crew was kind of useless.
What do think others contributors?
