### ISSUE TITLE
HTTPS by default

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#568]
We should consider this.
I don't know a lot about https and the issues we might encounter while trying to offer https by default, but I guess we will found most answer here https://github.com/isaacs/github/issues/156
Now that letsencrypt is in public beta, I hope that things might go evolve https://letsencrypt.org/2015/12/03/entering-public-beta.html

**Comment by leoderbois** [comment]
:+1:

**Comment by MoOx** [comment]
I tried cloudfare free offer for moox.io and phenomic.io with a single "page rule" to redirect all pages to https (eg: with the pattern "http://*moox.io/*"). If that works well, will do that for putaindecode.io asap.

**Comment by MoOx** [comment]
Boom https://github.com/blog/2186-https-for-github-pages

**Comment by MoOx** [comment]
Well it's only for *.github.io... Cloudflare can be an option then.

**Comment by bloodyowl** [comment]
can a LetsEncrypt do the job? anyone knows how to configure this stuff? @putaindecode/authors

**Comment by zoontek** [comment]
Maybe we could deploy to netlify.com?

**Comment by bloodyowl** [comment]
does this imply moving away from GHPages?

**Comment by zoontek** [comment]
Unfortunately, yes.

**Comment by bloodyowl** [comment]
maybe @MoOx will have some feedback with all the phenomic users

**Comment by revolunet** [comment]
also, zeit may offer free automated SSL and dns aliasing for static apps

https://zeit.co/pricing
<img width="704" alt="capture d ecran 2017-10-22 a 23 29 12" src="https://user-images.githubusercontent.com/124937/31866519-f68ca7b8-b780-11e7-845d-ea0e8a22fd8d.png">

**Comment by MoOx** [comment]
Go for netlify + free https (included). Netlify will even bring use a website per PR! How cool?

**Comment by lionelB** [comment]
> Netlify will even bring use a website per PR! 
that's cool !

**Comment by MoOx** [comment]
done depuis un moment
