### ISSUE TITLE
More than 3 articles in the Home page

### ISSUE THREAD

**Issue by leoderbois** [putaindecode/putaindecode.io#569]
Hi ! 

I think it can be great to have more than 3 articles visible in the main page. If your problem is "you can see old articles if there not a lot of new articles", it can be good to get something like :

```
if  (all articles in the last 2/3 months).count > 0
      return (all articles in the last 2/3 months) 
else 
     return (the 3 last)
```

Because, I published my article last week and it is not visible in 1 week, that's very frustrating and I'm thinking I'm not alone with this sadness. :stuck_out_tongue:

**Comment by MoOx** [comment]
Sure that's not enough. We should review this. 5, 6, 9 or 10...
Maybe two columns on desktop...

**Comment by MoOx** [comment]
Take the date in consideration is not really an option since we can have time where we don't update the site for a while. I used 12. Your posts will be visible when we will replace this on homepage and use categories.
