### ISSUE TITLE
Post : Hello Swift

### ISSUE THREAD

**Issue by leoderbois** [putaindecode/putaindecode.io#581]
Yop,

Je suis en train d'écrire un article sur les bases du Swift. J'aurai besoin d'avis !

En gros j'ai 2 grosses parties : les bases (variables,affichage/logs, conditions, boucles, fonctions, tableau) et les objets. Plus j'avance dans l'article plus je me dis que ça serait mieux de le couper en deux.  vu que swift est aussi un langage de script, on peut déjà jouer pas mal avec la bases sans les objets. Et puis ça permettrait peut être dans dire un peu plus sur les objets dans une articles plus ciblé et/ou ajouter des choses auquels j'aurai pas pensé sur les `bases`.  

Voici mon brouillon, si ça peut vous aider : https://www.dropbox.com/s/2kzfvmz7mfgoc7n/hello-swift.md?dl=0 (ceci est un gros brouillon sale sans relecture !)

Du coup : un ou deux articles ?

**Comment by MoOx** [comment]
D'un manière général, n'hésite pas à découper !

**Comment by Uhsac** [comment]
Découpé le en deux oui

**Comment by leoderbois** [comment]
Ok ! Merci ! bon bah je retravaille ça !

**Comment by Macxim** [comment]
:+1: pour le découpage.
Posts plus concis, plus rapides à lire et à assimiler et plus faciles à traduire.

**Comment by magsout** [comment]
je partage l'avis général.

**Comment by MoOx** [comment]
Closing in favor of #633
