### ISSUE TITLE
Repo is becoming too big

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#590]
I think it's related to gh-pages weight... 
Now that statinamic build the client website, it's a bit big for each publish.
Maybe it's time to use a orphan branch to deploy...

**Comment by MoOx** [comment]
Note: each time I git pull between a merge (and a publish) I get more than 1MB of data...

**Comment by MoOx** [comment]
Ouch.

```
❯ git clone https://github.com/putaindecode/putaindecode.io.git
Cloning into 'putaindecode.io'...
remote: Counting objects: 62507, done.
remote: Total 62507 (delta 0), reused 0 (delta 0), pack-reused 62507
Receiving objects: 100% (62507/62507), 86.85 MiB | 231.00 KiB/s, done.
Resolving deltas: 100% (31275/31275), done.
Checking connectivity... done.
```

86MB

**Comment by Nyalab** [comment]
![](http://cl.ly/2G0u1G2z2z0d/Screen%20Shot%202016-02-17%20at%2014.06.07.png)

thanks to @ooflorent help and this post https://github.com/CodeBlastr/Zuha/wiki/Git-Reduce-Repo-Size

**Comment by Nyalab** [comment]
not finished, i'm still working on it

**Comment by Nyalab** [comment]
![](http://cl.ly/3i250G451b19/Screen%20Shot%202016-02-17%20at%2014.28.02.png)
et voilaaaa

**Comment by MoOx** [comment]
Sorry but you didn't fix anything on the long run. This issue will come back. We should "just" stop versionning gh-pages. See https://github.com/tschaub/gh-pages/issues/48

**Comment by MoOx** [comment]
@ooflorent just shared this https://github.com/facebook/graphql/blob/e27c004cbc7f752b5ea816375215fe333e02c9e/package.json#L21
I can be nice to make this as a simple script. Maybe I will even include that in statinamic since it's a really small snippet :)

**Comment by MoOx** [comment]
I am unprotecting gh-pages branch so we can use this force push method.

**Comment by Nyalab** [comment]
:clap:
