### ISSUE TITLE
OMG -> LGTM

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#596]
This would totally help us to follow (and improve) our current workflow

https://lgtm.co/docs/approvals/

> In order to approve a pull request a maintainer should add a comment that includes LGTM, which stands for looks good to me. When two approvals are received the branch is unlocked and can be merged.

You can block (using protected branch github api) and unblock merge for a pull request. How cool is that?
Note: nobody will be able to merge a PR by itself using this. So we need to think about this twice.

**Comment by Nyalab** [comment]
totally cool :+1:

**Comment by lionelB** [comment]
> totally cool :+1:
I'm agree

**Comment by Nyalab** [comment]
i don't know if we can do this, (link has changed: https://lgtm.co/docs/overview/) because it would need to add all of us in a MAINAINERS file, and to update it each time, if you agree with this, i could do it

**Comment by MoOx** [comment]
What about this https://github.com/postcss/postcss.org/blob/master/.lgtm

**Comment by MoOx** [comment]
Approvals set to 2 for now, since there is not a lot of activity.
