### ISSUE TITLE
Post : Mettez-vous au TDD

### ISSUE THREAD

**Issue by Freezystem** [putaindecode/putaindecode.io#608]
Voila j'ai un draft déjà pas mal abouti sur le sujet et j'aimerai bien le proposer. Il reste la relecture et la traduction anglaise à faire mais globalement il est déjà pas mal abouti. 

Pour le titre je ne sais pas encore. C'est un article qui vise à répandre la bonne au sein de la communauté des devs web sur les avantages de ce type de méthodologie. J'aborde aussi le BDD rapidement et quelques variantes du TDD. On peut développer certains point mais l'article fait déjà 6 pages donc je suis ouvert aux propositions.

Pour la création de l'article j'avais une question, comme je fais parti des contributeurs à présent, est-ce que je fais juste une branche sur le repo de putaindecode et ensuite je fais une PR ou est-ce que je fais un clone sur mon username et je fait une PR ?

**Comment by magsout** [comment]
Çà me plait bien ce sujet.

> On peut développer certains point mais l'article fait déjà 6 pages donc je suis ouvert aux propositions.

Préférez les articles courts, hein, trop long c'est imbuvable et on lit pas tout. Pas obligé de raccourcir, mais ça peut faire une série d’article. 

>Pour la création de l'article j'avais une question, comme je fais parti des contributeurs à présent, est-ce que je fais juste une branche sur le repo de putaindecode et ensuite je fais une PR ou est-ce que je fais un clone sur mon username et je fait une PR ?

Tu peux créer une branche direct sur le répo, et faire une PR ensuite.

**Comment by Freezystem** [comment]
Cool. Bah je vais créer la branche. Comme ça tu pourra jeter un coup d'oeil à l'article si ça te dis et proposer un découpage. J'suis assez d'accord avec ton point de vue, un article à suite c'est bien plus sympa et ça évite le décrochage massif. 
Du coup je suppose que ça impliquera une hiérarchie spécifique dans le répertoire du post. Je veux bien que tu m'explique si tu sais comment faire.

**Comment by MoOx** [comment]
Les contributeurs n'ont pas encore les droits pour le moment #552

**Comment by Freezystem** [comment]
Ah ok. Bon bah je pars sur un fork alors.

**Comment by magsout** [comment]
@MoOx 
>Les contributeurs n'ont pas encore les droits pour le moment #552

Oups, au temps pour moi.. Bon bein @Freezystem faudra que tu fork (déjà fait) et propose une PR depuis ton fork.

>Du coup je suppose que ça impliquera une hiérarchie spécifique dans le répertoire du post. Je veux bien que tu m'explique si tu sais comment faire.

Pas de hiérarchie particulière, on fera comme les post sur ES6. Un répertoire et tous les article dedans. Après pour le reste ça dépendra de comment tu souhaites fractionner ton article.

**Comment by MoOx** [comment]
Je pense effectivement que tu devrais y aller par petit bout, ça facilite et les review, relectures et traductions si besoin.
Tu peux aussi partager ton plan ici. Tu vas parler technique ou juste concept?

**Comment by Freezystem** [comment]
> Tu peux aussi partager ton plan ici. Tu vas parler technique ou juste concept?

Plus concept. Mais j'ai prévu un petite demo. J'ai fais une première mise en forme. Je vais poster la PR et attendre vos suggestions pour le découpage. Je ferais le refacto en fonction de vos retours. 

Il risque de toute façon d'y avoir des choses à améliorer. Je pense notamment au manque de références et de lien externes sur les acronymes et termes importants.

**Comment by Macxim** [comment]
Top ça :+1:

**Comment by Freezystem** [comment]
> Ça me plait bien ce sujet.

> Top ça :+1:

@Macxim & @magsout : Si vous voulez participer, ajouter d'autres points de vues ou détailler d'autres méthodologies sentez vous libre de le faire, ça serait super cool et augmenterai l'impact de l'article.

**Comment by n1c01a5** [comment]
Déjà c'est une très bonne idée de faire une série d'articles sur le TDD à mon sens :+1: . J'ai lu le premier article https://github.com/Freezystem/putaindecode.io/blob/post.tdd/content/fr/articles/tdd/se-lancer-dans-le-tdd-definitions-et-variantes/index.md j'ai quelques remarques à faire :
1) Je trouve qu'il y a trop d'idées dans ton introduction (les fonctions comme test, la nature méfiante de l'Homme, la permissivité des standarts du web, la demande croissante de qualité de code des entreprises et le caractère agile du TDD). Il serait peut-être souhaitable de choisir un seul point et de le développer. De plus, tous les points que tu abordes concernent davantage les tests en général que le TDD mais c'est c'est une bonne transisition pour le TDD. Il serait possible de faire une intro du type
    Inutile de vous rappeler l'intérêt de faire des tests. Bon... un petit rappel
- lister les avantages...
Mais pourquoi pas les écrire avant. Ce qui... (lister les avantages)
2) D'ailleurs parmi les avantages, il serait de dire que cette méthode permet de définir clairement les objectifs à atteindre pour le dévoloppeur et peuvent aussi constituer une documentation avant la feature.

**Comment by bloodyowl** [comment]
Closing in favour of #703
