### ISSUE TITLE
Use mention-bot for code review (not post review)

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#613]
Just an idea

https://github.com/facebook/mention-bot

**Comment by Nyalab** [comment]
why not, i like this project, do you want to use the default hosted heroku one since we do not own a proper server?

**Comment by Nyalab** [comment]
https://github.com/putaindecode/putaindecode.io/commit/1d2aa375f34ac5807c25a709b9046dfe8d845e29
https://github.com/organizations/putaindecode/settings/hooks/7058803

**Comment by MoOx** [comment]
:+1:
