### ISSUE TITLE
Post: Angular 1.5 - Un pas de plus vers les web components

### ISSUE THREAD

**Issue by Freezystem** [putaindecode/putaindecode.io#621]
J'ai commencé la rédaction d'un article sur `angular.component()` qui sortira avec la version 1.5 du framework. Il manque juste la version traduction anglaise que je ferai dans la foulée si le post est accepté.

**Comment by MoOx** [comment]
Closed by 39fd78fa52d9d79635421a693089d86fb53f7b75
