### ISSUE TITLE
Add an issue_template.md

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#634]
https://github.com/dear-github/dear-github/issues/125

Might be done with the doc and probably just some links to en and fr doc version.

**Comment by ooflorent** [comment]
There is now an article about it: [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates).

**Comment by magsout** [comment]
:+1:

**Comment by Nyalab** [comment]
we are not shipping software within this repository, so we do not have this kind of issue, but this could be useful, it is better than nothing :+1:
