### ISSUE TITLE
top contributors should be owners of putaindecode organisation

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#638]
In addition to https://github.com/putaindecode/putaindecode.io/issues/527 I think it will be a good idea to make this a reality.
We can decide to update owners twice a year, I would say that march and september will be nice period of the year to do that.
Currently the top contributors on the last 6 months are

@MoOx @Macxim @magsout @Nyalab @naholyr @zoontek @bloodyowl @lionelB.

What do you think guys?

(=> you can be owner (if not already), just say "I am in" or "thanks, no interested").

Being an owner involve... not that much. Maybe a more important voice for big decisions. And we have to split 60€ for domains each years :D

**Comment by lionelB** [comment]
agree with that 
(even if I'm not owner, I'm still interested in participate to domain fees)

**Comment by MoOx** [comment]
@lionelB You are an owner already https://github.com/orgs/putaindecode/people?utf8=%E2%9C%93&query=role%3Aowner (link works if you are in the org)

**Comment by Nyalab** [comment]
@lionelB :facepalm:

**Comment by lionelB** [comment]
> (even if I'm not owner, I'm still interested in participate to domain fees)
 il manquait in `the future`. BANDE DE FILS DE PARALLÉPIPÈDE !

**Comment by zoontek** [comment]
I'm totally OK with that, will easily donate for domain fees

**Comment by ooflorent** [comment]
GIMME COMMIT RIGHTS

**Comment by MoOx** [comment]
You will have when we handle #552. Oh but you didn't write any post yet?

**Comment by Macxim** [comment]
It seems like the logical thing to do :+1:

**Comment by magsout** [comment]
oh yeah :+1: seems totaly fair ..

**Comment by bloodyowl** [comment]
:shipit:

**Comment by naholyr** [comment]
I'm in, simplifies the global contribution process and it's cool go share the cost. Given my availability I doubt I will be there more than 6 months but the rule is pretty clean.

**Comment by MoOx** [comment]
Let's do this. I will document this workflow  asap.

**Comment by MoOx** [comment]
@naholyr @zoontek Added as owner on GitHub. Feel free to ask all admin right/access for twitter, facebook etc. For the discord channel (you are not in, but you can join by clicking the chat icon on the website header) you can become admin by asking this too.

@_kud Removed as owner. Feel free to continue to contribute to this project like you did in the past. That said, you will still have write access according to #552 ;)

**Comment by MoOx** [comment]
@kud Removed as owner. Feel free to continue to contribute to this project like you did in the past. That said, you will still have write access according to #552 ;)

**Comment by MoOx** [comment]
(I reposted since I used @_kud instead of @kud, sorry for missing that)

**Comment by kud** [comment]
No worries. Thanks for the notification. Yes, let's try like that. ;)

**Comment by bloodyowl** [comment]
already the case
