### ISSUE TITLE
Markdown files should have title level 2 only

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#642]
Currently it seems we have some files that have some level 1 but they should not.

I see two solutions: 
- add a linter that yell on level 1
- transform level 1 to 2, 2 to 3 etc (via remark/mdast).

I think the automatic solution make more sense for a good UX.

**Comment by magsout** [comment]
Linter is better IMO. force user to make goood code..

**Comment by magsout** [comment]
And especially why. The linter explains why the code is not good.

**Comment by MoOx** [comment]
Yeah but maybe enhancing UX by converting level to what we need is even better (and starting with level 2 in post is a bit weird to be honest).

**Comment by bloodyowl** [comment]
turbo osef
