### ISSUE TITLE
Update link "Tous les contributeurs" to point to github contributions WITH DATE

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#643]
eg: https://github.com/putaindecode/putaindecode.io/graphs/contributors?from=2014-10-24&to=2016-01-15&type=c instead of https://github.com/putaindecode/putaindecode.io/graphs/contributors

The date range should reflect the period used for the top contributor things (latest 6 months currently).

**Comment by magsout** [comment]
The link is: _tous les contributeurs_ why do you want to specified a date ?

**Comment by MoOx** [comment]
To reflect the "top contributors" order. But maybe this is stupid. Even more if we consider #527
