### ISSUE TITLE
Should we talk french in our issues/PRs/commits?

### ISSUE THREAD

**Issue by Nyalab** [putaindecode/putaindecode.io#645]
The main audience for our website is french. If we want to brought in the more people we can, we should talk in french, so people can contribute to the elaboration of the content and the structure of it.

I rooted for english at the start, but now, i cannot see the benefits of it, besides adding an obstacle for our community.

What do you think?

**Comment by ooflorent** [comment]
As long commits and code remain in English...

**Comment by lionelB** [comment]
C'est *good* pour *me*

**Comment by MoOx** [comment]
Most content on github is in english. We can talk in french when someone start an issue/pr in french, but for the rest, I will continue to english. As @ooflorent said, the code is in english.

**Comment by magsout** [comment]
pr in french (post): je parle français
issue/pr in english and autor starts in english: I speak english

**Comment by Nyalab** [comment]
@ooflorent the code ofc, but i don't think for commits and PRs
@MoOx most content on github is in english because projects are meant to have a worldwide audience, here we clearly see that people that helps us are french, and that if we want to bring people with us, we could talk french to ease the interaction with the community, so more people could just talk in issues, PRs, do reviews, and so on
@magsout yes but it is so because we put up rules, not because people chose to do so

i think the default should be french, and if someone begins to talk in english in the opening of its issue or PR, keep talking in english

**Comment by magsout** [comment]
>i think the default should be french, and if someone begins to talk in english in the opening of its issue or PR, keep talking in english

Yep, sgtm  :+1:

**Comment by Nyalab** [comment]
ok, so we agree ? we can talk french in french posts, issues, and PRs, but we keep the code in english aswell as the english posts ofc

**Comment by MoOx** [comment]
well d'accord. Faut qu'on documente tout ça du coup tant qu'à refaire la doc de contrib

**Comment by Nyalab** [comment]
Comme tu peux le voir j'ai encore poussé sur la PR de documentation, je pense que si tout est en français les gens parleront en français (par contre si quelqu'un veut m'aider pour traduire la doc en anglais, parce que je ne le ferais pas). Mais je l'ajouterais :)

**Comment by lionelB** [comment]
super @Nyalab , pour la traduction, poke @skinnyfoetusboy, peut être qu'il peut donner un coup de main.

**Comment by MoOx** [comment]
Je m'occuperais de la trad si besoin

**Comment by MoOx** [comment]
Je regarderais ca :)

**Comment by bloodyowl** [comment]
osef
