### ISSUE TITLE
Only use fastmerge for merging?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#646]
fastmerge: script to easily merge a PR like this

fastmerge -r origin {PR URL}

https://github.com/vitorgalvao/tiny-scripts/blob/master/fastmerge

Result: https://github.com/putaindecode/putaindecode.io/pull/633#issuecomment-190602015

**Comment by MoOx** [comment]
Pro: this avoid merge commit
Con: NO BUTTON

**Comment by Nyalab** [comment]
sorry but i really don't see the point, we don't care about a commit in the history, on the contrary, we have the link to the PR within

**Comment by MoOx** [comment]
![dontgiveafuck](https://cloud.githubusercontent.com/assets/157534/13427591/58915846-dfb5-11e5-8399-01fb426a273a.gif)

**Comment by Nyalab** [comment]
only you can make me laugh this often a day :smile:
