### ISSUE TITLE
Change base password for all accounts and update outdated emails

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#650]
See accounts.json

**Comment by Nyalab** [comment]
:+1:, keep public part on GH, private on GDocs :ok_hand:

**Comment by MoOx** [comment]
Gdocs is probably oudated, and so should be dropped.
I will do this and send the new base password by email to the owners. Currently documenting this in a private note, but will make the entire "owners" upgrade process public.

**Comment by Nyalab** [comment]
can't wait! :trollface:

**Comment by MoOx** [comment]
🖕
