### ISSUE TITLE
Field "approvers"

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#673]
Here is an idea: add an "approvers" field (array of nicknames, like reviewers) à la "recommended by" that you can find on medium.
The difference with a "reviewers" is that people can strongly say "I totally approve the idea of this post", which can be different from a reviewer (that can just means "the ton is correct, not too much typo").

Thoughts?

**Comment by Nyalab** [comment]
i find it useless, sorry  ¯\_(ツ)_/¯
