### ISSUE TITLE
2 links in webhook post are 404

### ISSUE THREAD

**Issue by Uhsac** [putaindecode/putaindecode.io#675]
In this article : http://putaindecode.io/fr/articles/github/webhooks/

2 links at the bottom of the page redirect to 404:

- http://putaindecode.io/fr/articles/github/webhooks/header.txt
- http://putaindecode.io/fr/articles/github/webhooks/payload.json

**Comment by lionelB** [comment]
thanks for the reports !

**Comment by MoOx** [comment]
Closed by de054a6ecb1bfb2c88fa250aebb8cb05913d5ec1
