### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by dialgui** [putaindecode/putaindecode.io#678]
http://putaindecode.io/fr/articles/

**Comment by MoOx** [comment]
Probablement une erreur temporaire.

![screen shot 2016-06-23 at 16 34 34](https://cloud.githubusercontent.com/assets/157534/16307122/661a2e5c-3960-11e6-82cc-5c1642a005a8.png)

Tu peux réessayer?

**Comment by MoOx** [comment]
Fonctionne très bien, ça devait être un petit outage github.
