### ISSUE TITLE
Post : Tutoriel Express JS et Mongoose

### ISSUE THREAD

**Issue by Ananasr** [putaindecode/putaindecode.io#679]
Bonjour ! Je suis actuellement en train de coder un petit tuto sur comment faire rapidement une API REST à l'aide d'Express JS et Mongoose. Trouvez-vous ça intéressant ?

**Comment by MoOx** [comment]
J'ai pas trop de recul sur les bests practices pour faire une API mais si t'as quelques sources intéressantes pourquoi pas :)

**Comment by bloodyowl** [comment]
Bonne idée, ce serait intéressant de présenter un exemple d'implémentation d'API REST avec Express/Mongo avant de présenter l'équivalence avec Express/Mongo/GraphQL.

**Comment by Ananasr** [comment]
Cool ! Je me lance et reviens vers vous dès que j'ai un truc qui ressemble à quelque chose ;)

**Comment by bloodyowl** [comment]
@Ananasr toujours d'actualité ?

**Comment by Ananasr** [comment]
Yep ! Faut que je retrouve où je l’ai fichu ... ça arrive vite !

**Comment by bloodyowl** [comment]
any news?

**Comment by MoOx** [comment]
PR welcome :)
