### ISSUE TITLE
Post : React + mjml server side 

### ISSUE THREAD

**Issue by magsout** [putaindecode/putaindecode.io#680]
Une introduction sur l'envoie d'e-mail avec utilisation de React + mjml et quelques autres tools, server side bien sur.  

Oui ? Non ?

**Comment by MoOx** [comment]
👍

**Comment by bloodyowl** [comment]
Yup, bonne idée

**Comment by magsout** [comment]
Bon je close, n'utilisant plus mjml pour une histoire de bug, je ne vois plus l’intérêt d'un article.

**Comment by revolunet** [comment]
😢 du coup tu as fait comment ca m'intéresse ? :p

**Comment by bloodyowl** [comment]
ça peut quand même valoir le coup de faire un petit retour d'expérience avec positif/négatif nan ?

**Comment by bloodyowl** [comment]
l'ayant un peu utilisé j'en ai deux trois aussi (genre sympa à utiliser mais à tweak après parce que les defaults sont chelou)
