### ISSUE TITLE
Laravel Framework

### ISSUE THREAD

**Issue by M4gicT0** [putaindecode/putaindecode.io#682]
Il me semble qu'il n'y a aucun article sur Laravel, et moi je suis motive pour en ecrire un ! Ca interesse ? Francais / Anglais peu importe.

**Comment by MoOx** [comment]
J'y connais rien en Laravel perso. @zoontek ?

**Comment by zoontek** [comment]
@M4gicT0 Ça serait pour faire quel type de tuto?

**Comment by M4gicT0** [comment]
Bah plutot une presentation du framework et ma vision des choses

**Comment by zoontek** [comment]
Il y a pas mal à couvrir… Tu peux faire un draft et me pinguer pour la relecture / des questions 😀

**Comment by bloodyowl** [comment]
@M4gicT0 toujours d'actualité cette proposition ?

**Comment by M4gicT0** [comment]
Uhm je pense pas avoir le temps finalement... A voir si ca interesse vraiment

**Comment by bloodyowl** [comment]
Ok, pas de souci 😊

**Comment by groovytron** [comment]
Bonjour. Si vous y voyez un intérêt, je peux voir pour faire un article. Je ne suis pas un expert en Laravel mais j'ai réalisé deux projets avec ce Framework dans le cadre de mes études en 2016 - 2017; un [projet «simple»](https://github.com/HE-ARC/lenspector) ou je n'ai pas utilisé de fonctionnalités avancées et un projet où j'ai utilisé leur fonctionnalités de [queue/workers](https://laravel.com/docs/5.5/queues).
Je dois regarder mon emploi du temps mais je pourrais démarrer la rédaction de l'article vers fin novembre. Je suis plus à l'aise en français mais une rédaction en anglais est aussi possible (ça me fera bosser mon anglais au pire).
@M4gicT0 tu avais déjà des idées?
