### ISSUE TITLE
POST : L'intégration continue avec Jenkins et AC2

### ISSUE THREAD

**Issue by YannGrosjean** [putaindecode/putaindecode.io#700]
Salut tout le monde ! 
Un article sur la mise en place d'un serveur d'IC Jenkins sur les serveurs d'Amazon pourrait-il vous intéresser ? Je vais devoir le mettre en place pour un projet, et je me suis dit que ça pourrais faire un tuto sympa. 

Pour l'instant ça reste un projet, je détaillerais la procédure complète au fur et à mesure de mon avancé. A priori, si des exemples sont explicités, ce sera sûrement avec du PHP, mais rien n'empêche d'adapter à d'autres technos !

Let me know ! ;)

**Comment by MoOx** [comment]
Pourquoi pas :)

**Comment by bloodyowl** [comment]
Ça ferait un article intéressant. On attend ta PR 😊

**Comment by bloodyowl** [comment]
@YannGrosjean cette proposition est-elle toujours d'actualité ? Si oui penses-tu que ce sera jouable pour mi-novembre ?

**Comment by YannGrosjean** [comment]
Houla j'avais oublié ça ... Hum, j'aimerais vraiment prendre le temps pour écrire cet article, mais non je ne peut en aucun m'avancer sur la date pour l'instant :/

**Comment by bloodyowl** [comment]
bon ben je close en attendant, en espérant que tu trouves le temps 😃

**Comment by YannGrosjean** [comment]
Merci bien ! Oui j'adorerais !
