### ISSUE TITLE
Un article sur Polymer 

### ISSUE THREAD

**Issue by scenaristeur** [putaindecode/putaindecode.io#712]
Bonjour, 
personne ne parle de Polymer (https://www.polymer-project.org/1.0/)... c'est à bannir comm jQuery, ou bien ???

**Comment by lionelB** [comment]
Hello,

Si tu souhaites faire un article sur polymer, je pense qu'il sera le bienvenu. Le fait qu'on en parle pas est surtout du au fait que la plus part des auteurs sont sur une stack react :)

**Comment by magsout** [comment]
Moi ça m’intéresse pour ma culture.. J'avais suivi le projet au début mais je crois qu'ils ont pris une nouvelle direction plus composant à la React.. non ?

**Comment by bloodyowl** [comment]
Je ferme l'issue faute d'article. Je réouvrirai si quelqu'un est chaud pour s'y lancer.
