### ISSUE TITLE
Build est tout cassé

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#725]
https://travis-ci.org/putaindecode/putaindecode.io/builds/234810157#L205

A voir si c'est une histoire de token ou d'api qui a changé (l'api github venant d'etre update).

**Comment by bloodyowl** [comment]
ça pète depuis plusieurs posts, j'ai publisher à la mano à chaque fois

**Comment by MoOx** [comment]
Jregarde ça dès que j'ai un peu de temps.

**Comment by MoOx** [comment]
ET SINON CA T'ES PAS VENU A L'IDEE DE FAIRE UN REPORT DE BUG MATTHIAS?

**Comment by MoOx** [comment]
Fixed. J'avais nettoyer tous les tokens github de mon côté (car pas de labels). Ca remarche now.
