### ISSUE TITLE
POST : faire fonctionner create-react-app avec une API, en développement

### ISSUE THREAD

**Issue by tmaziere** [putaindecode/putaindecode.io#728]
Bonjour,

Suite à une session de travail qui nous a fait restructurer notre code en dev pour pouvoir faire fonctionner en local une appli React avec notre API (sur deux ports différents), tout en conservant deux repos distincts, je propose de rédiger un retour d'expérience.

[Cet article](https://www.fullstackreact.com/articles/using-create-react-app-with-a-server/) nous a beaucoup inspiré, je le précise.

On trouve que c'est fichtrement utile pour le dev front, mais à vous de nous dire :)

**Comment by MoOx** [comment]
Pourquoi pas.
Un plan à partager?

**Comment by tmaziere** [comment]
Je pensais à quelque chose comme ça, par exemple :

### Organiser son code pour développer avec Create React App et une API Node.js

1. Est-ce que ça me concerne ?
2. Deux dépôts : le frontend, l’API
3. Organisation locale du code
4. Passez moi sur le CORS
5. Tout lancer en une seule commande
6. Configurer le build React

**Comment by bloodyowl** [comment]
@tmaziere Est-ce que tu penses qu'il serait possible d'avoir ce post prêt pour début novembre ?

**Comment by tmaziere** [comment]
@bloodyowl pour la semaine du 6, c'est jouable de mon côté.

**Comment by bloodyowl** [comment]
top, merci ! je t'ajoute au planning pour le 14 novembre (ça laissera le temps pour la review)

**Comment by tmaziere** [comment]
@bloodyowl Ma proposition d'article est [disponible ici](https://github.com/tmaziere/putaindecode.io/blob/create-react-app-et-api/content/fr/articles/js/react/create-react-app-et-api/index.md).

Dois-je faire une PR dès maintenant ?

**Comment by bloodyowl** [comment]
@tmaziere hey, cool ! effectivement, il faudrait que tu PR qu'on puisse review le post et le planifier pour la publication 👍

**Comment by tmaziere** [comment]
@bloodyowl c'est fait !

**Comment by bloodyowl** [comment]
merged in prod
