### ISSUE TITLE
POST : Series d'articles sur les Observable

### ISSUE THREAD

**Issue by MrWi2l** [putaindecode/putaindecode.io#729]
Hello !
J'aimerais me lancer dans la redaction d'une série d'articles sur les Observable sous forme de chapitres 💯 

1. Qu'est ce que les Observable(Le squelette, les ossements, la composition chimique...)
2. Presentation de RxJS et de quelques opérateurs pratiques
3. L'utilisation des Observable avec une application React/Redux

Dites moi ce que vous en pensez ;-)

**Comment by MoOx** [comment]
Je n'utilise pas du tout donc je ne saurais aider pour la rélecture sur le fond mais pourquoi pas.

**Comment by lionelB** [comment]
j'utilise un peu donc tu peux me pinger quand la PR sera prête

**Comment by wyeo** [comment]
C'est noté, merci

**Comment by wyeo** [comment]
https://github.com/putaindecode/putaindecode.io/pull/732

**Comment by MoOx** [comment]
N'hésite pas à continuer si tu en as envie :)
