### ISSUE TITLE
ajouter le média dans le flux rss

### ISSUE THREAD

**Issue by bodtx** [putaindecode/putaindecode.io#730]
Afin de pouvoir ajouter votre podcast dans un gestionnaire de podcast, il faudrait que vous ajoutiez le média dans le flux rss comme ce qui est fait ici:

http://lescastcodeurs.libsyn.com/rss

**Comment by bloodyowl** [comment]
Le feed du podcast est sur SoundCloud, on parle du flux RSS global du site là ?

**Comment by MoOx** [comment]
Surement

**Comment by MoOx** [comment]
le rss a été revu, réouvrir si besoin avec plus de détail
