### ISSUE TITLE
Virer le contenu en + es

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#739]
Y'a quelques vues, je trouve ça dommage de juste jeter.

Je propose les choses suivantes:

- proposer aux auteurs de récup leur posts en/es
- si ça a été traduit (pas mal par moi je crois), je peux récup les contenus sur mon blog (avec les bon crédits)

Du coup on fait des redirections en/* (via html meta, google ça lui suffit comme une 302) vers les posts bougés (je pourrais m'occuper de tout ça très rapidement - genre dans la semaine)
Et pour fr/* on laisse comme ça le temps du redesign (+phenomic 1.x) mais faudra prévoir une redirection (via phenomic on pourras supporter redir via rr3 et générer des html meta pour faire fr/* => *)

Qu'es vous en dites? En gros je propose de m'occuper de tout ça vu que c'est moi qu'est fait chier avec.

**Comment by bloodyowl** [comment]
pour 1 000 vues/mois sur `/en` j'sais pas si ça vaut vraiment le coup. mais effectivement on peut proposer aux auteurs de récupérer les posts

**Comment by MoOx** [comment]
C'est pour ça je propose de m'en occuper vite fait.

**Comment by leoderbois** [comment]
Avis perso : il y a des milliers de site de dev EN ou ES. Mais peu de site FR **collaboratif** comme celui-ci. Avoir un contenu FR de qualité est bien plus intéressant et rare

**Comment by bloodyowl** [comment]
Ouais, on a itéré pour tester, avec des efforts de plein de gens pour tenter le coup, malheureusement pour faire un vrai blog multilingue avec des posts traduits, ça demande beaucoup de temps et d'énergie, trop pour l'instant pour que ça vaille le coup.

On préfère se focus sur l'animation de la communauté, de nouveaux formats comme le podcast et la vidéo, et de nouveaux sujets, mais ça on communiquera rapidement dessus 🤐

**Comment by MoOx** [comment]
@bloodyowl done du coup?

**Comment by MoOx** [comment]
moi: oui
