### ISSUE TITLE
Retours à propos de "La fonction: une closure particulière"

### ISSUE THREAD

**Issue by xvw** [putaindecode/putaindecode.io#747]
Bonjour, 
Je suis conscient que ce genre de retour pourrait être fait dans un commentaire (sur la page), 
cependant, je pense que pour que la discussion soit plus facilement étendue, ce n'est pas un 
mal de le faire ici (d'autant plus que @bloodyowl ne semblait pas en désaccord avec l'idée). 
J'aurais aussi pu ouvrir une PR, cependant, je n'ai pas de correctifs ponctuels à formuler. 

### Avant-propos

Ce message fait écho à l'article http://putaindecode.io/fr/articles/swift/closure/ publié par 
@leoderbois. Avant de dire quoi que ce soit, j'aimerais tout d'abord souligner quelques points 
qui motivent (et qui expliquent) ma démarche. Tout d'abord, je suis très heureux de voir un 
espace de publication francophone qui se fixe l'objectif de publier des articles de qualités et 
je suis très heureux de voir des ressources sur Swift, en français, voir le jour. C'est en partie 
parce que je trouve que la motivation derrière l'écriture de ce genre d'article est admirable que 
je me permet de prendre le temps de faire un retour (qui pourra peut être passé comme 
"assez dur"). De plus, je me permet de souligner que **je n'y connais rien en Objective-C, Swift**
et en règle général en développement mobile. De ce fait, il est possible que certaines choses 
que je vais évoquer passent pour des énormités et il est important de comprendre que mon 
avis est **celui d'un néophyte qui découvre Swift au travers de ces articles**.
Cordialement, Xavier. 

### Un titre ambigu 

Il s'agit d'un avis très personnel, mais j'ai l'impression que le titre est... particulièrement formulé.
 En effet, il me semble que `Swift - la closure, une fonction particulière` serait plus pertinent. Parce 
que, même si je pense que fondamentalement, tu as raison, les fonctions "nommées" sont un 
cas particuliers de l'usage des *lambdas*, on est, en tant que programmeur, généralement 
confronté à l'usage de "fonctions normales" avant d'utiliser des lambdas, de ce fait, je pense 
qu'inverser les propositions ne serait pas un mal ! 
Principalement parce que ton article développe surtout l'utilisation de lambda, mis comme une 
extension  aux fonctions "normales".

### Plusieurs objectifs

Le deuxième point porte sur l'objectif de l'article, je dois avouer qu'à la lecture, j'ai trouvé que 
tu essayais de défendre plusieurs postulats (tous potentiellement vrai hein) : 

- Bonne pratiques (nommer les arguments pour documenter une fonction)
- Apprendre le b-à-bas de la programmation (description fondamentale d'une fonction)
- Le typage (tuple et type fonctionnels)
- Les clotures et la notion de portée (lexicale ici)

Je pense que le fait que tu tâches de couvrir tout ces points rend l'article complexe à suivre. 
Je ne te jette pas du tout la pierre, je trouve que c'est généralement la partie la plus difficile 
dans la rédaction d'un article, c'est d'aller à l'essentiel de ce que l'on a envie de transmettre.

### On passe a coté de l'intérêts des clotures

Le dernier point, qui me semble le plus important, c'est que, **à mon sens**, tu passes totalement 
à côté de l'intérêt d'une cloture, en présentant beaucoup de cas insensés et marginaux qui 
portent principalement sur la définition morphologique (ou parfois via le type) des clotures. 

Dans un langage qui permet la manipulation de lambda, on a généralement, en plus, la notion 
de "fonction d'ordre supérieur", soit la capacité à "envoyer" des fragments de codes contextuels. 
Les exemples les plus communs sont map/filter/reduce/count etc. Ici, l'article n'en parle pas du 
tout.  (Je pense que, d'ailleurs, la documentation de Apple sur Swift (qui une fois de plus a été 
généreux :D) propose beaucoup d'exemples intéressants : 
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Closures.html)

Pour conclure, je pense, désolé, que cet article devrait être restructuré, repensé pour transmettre
les points essentiels des clotures, tout en évitant quelques erreurs "théoriques" (comme la 
définition même de la cloture, les comparaison hasardeuse avec d'autres objets similaires dans 
d'autres langages faisant gagner à l'article beaucoup de clarté sur "les mutations de scopes", 
"l'encapsulation d'environnement" et l'intérêt réel des clotures. 

J'espère que cette issue ne sera pas mal perçue, sinon, je ne me formaliserai pas du tout de sa
fermeture/suppression. 

Cordialement, Xavier !

**Comment by leoderbois** [comment]
Bonjour,
Merci pour ce retour bien travaillé :)

Honnêtement, ce titre vient de mon manque d'inspiration, mais je suis pas d'accords non plus avec le titre que tu proposes car il est faux. Même si je suis d'accords avec toi sur l'ordre d'apprentissage en général, quand on lit le livre d'apprentissage d'Apple il est bien dit que la fonction est un sous ensemble de la Closure, et je refuse de faire un petit mensonge pour la simplification ^^

Je suis assez d'accords avec le reste de ce que tu dis. Mais l'objet de l'article est plus orienté pour les débutants, et du coup j'ai peut être mélanger une notion avancée et un notion débutante dans le même article. Le but n'était pas de parler que des closures, mais aussi montrer la base des fonctions. C'est pourquoi je voulais pas parler de map/filter, car il aurait fallu expliquer beaucoup plus de chose pour monter 2 notions. 

`On passe a coté de l'intérêts des clotures`

Tu vois les closures comme une lambda, c'est à dire que les cas récurrents d'utilisation des lambdas sont souvent pour les tris, maps, filters. Hors réduire les closures à ça, c'est perdre énormément d'utilité dans la `feature`car : 

- dans 90% des cas de tri/filter/map, en Swift, la notion de variable-fonction n'est pas visible car on code comme ça : `reversedNames = names.sorted(by: { $0 > $1 } )` donc aucune notion de variable n'est pas utilisé (`let monTri = ...`)

- la closure sert beaucoup à échanger du code entre objets, par exemple comme handler entre deux contrôleurs, et ici la notion de variable-fonction est vraiment utilisé (`objectA.handler = objectB.updateUI). 

Donc c'est plus proche des cas d'utiilsation des `block C++` de `LLVM` qu'au lambda. A mon gout, limiter les closures au cas particulier des tris/filters c'est comme limiter la notion d'objet à un encapsuleur de donnée (en oubliant l'héritage, la notion de pointeur...) même si la doc d'Apple comment par ça.

Je voulais dans cette article : 

- expliquer la fonction en Swift
- une fonction peut être une variable 

Du coup, si je devais modifié quelque chose se serait le titre pour pas autant "induire" dans la notion de Closure dès le début et supprimer la phrase sur les lambdas car réduire la closure aux cas récurrents des lambdas serait vraiment perdre en "fonctionnalité" de la `feature`. Et faire une article peut être plus poussé sur les cas d'utilisation des Closures si ça peut intéresser. 

Tu en penses quoi ? @bloodyowl, @MoOx vous ne pensez quoi ?

**Comment by xvw** [comment]
Merci d'avoir pris le temps de me répondre : 

>  je refuse de faire un petit mensonge pour la simplification ^^
Et que penserais-tu de "Fonctions et Closures en Swift" alors ? 

> Tu vois les closures comme une lambda
C'est parce que **c'est une lambda**. Une des propriété principale de la lambda c'est 
de capturer son environnement, et de pouvoir être considérée comme une valeur. 
L'utilisation des `{$0...}` c'est un sucrage syntaxique qui existe depuis Smalltalk, qui 
devait être, initialement, un Lisp avec des objets, et où les blocks sont arrivés 
uniquement pour faciliter l'écriture des paramètres "qui agissent" sur l'état encapsulé 
par un objet. C'est d'ailleurs une approche similaire qu'a utilisé Scala. 

Par contre, je vois ce que tu veux dire, et je comprend mieux l'objectif de l'article. Tu 
sembles vouloir proposer l'utilisation des clotures comme une manière propre de faire 
de l'injection de dépendances (et par extension, tendre vers de la programmation par 
domaines), c'est une excellente idée mais je reste convaincu que l'article devrait, via des 
exemples "plus réalistes", tendre vers cet objectif. 

Si je devais écrire un article qui traiterait de ce sujet, je verrais ces plusieurs points : 

-  Définition et usages des fonctions 
-  Définitions et usages "simples" des clotures : 
     - comparées aux fonctions normales (utilisées comme des fonctions normales)
     - High Order functions (map par exemple, et explication du sucrage `{}`
-  Mutation de scopes (échange de code) 
-  Exemple concret

Merci de ta réponse.

**Comment by leoderbois** [comment]
Le truc c'est que, je pense, tu vois l'article comme quelqu'un qui connait bien la programmation, alors que je voulais l'orienté pour un débutant. Et si tu parles `High Order functions` et  de sucrage syntaxique, le débutant va juste lâcher l'affaire^^ 

Mon objectif, c'est d'écrire quelques articles sur les bases de Swift pour permettre de faire une application iOS ou un script pour un serveur Linux. Par exemple le prochain est sur les `Class` et `Struct`. Si je rentre dans des notions trop complexe dès le début, j'ai peur de perdre les gens et de me perdre parce que je suis un bon technicien mais pas un bon théoricien ^^

> "plus réalistes"

Je suis pas sur que des exemples sur les filters/maps soient plus réaliste, car j'ai utilisé les filters/maps avec `{$0...}` bien avant de savoir ce qu'été une closure car j'avais pas besoin de le savoir. 

Après honnêtement, je me vois pas ré-écrire l'article en entier (pas le temps principalement). Pour moi j'ai abordé les points que je voulais aborder de la manière dont je voulais les aborder. L'article n'aurait pas été clair, j'aurai essayé, mais la j'ai surtout l'impression que de ton point de vue, l'article va pas assez loin pour toi ? 
Après rien nous empêche de bosser sur un autre article, tout les deux, pour aller plus loin ?

**Comment by xvw** [comment]
Je ne voulais pas particulièrement que tu ailles plus loin. Je comprend tes points de vues 
sur la cible. Par contre, quand je parlais d'exemple plus réalistes, je pensais vraiment à 
des exemples utiles concernant ce point : 

>la closure sert beaucoup à échanger du code entre objets, par exemple comme handler entre deux 
> contrôleurs, et ici la notion de variable-fonction est vraiment utilisé (`objectA.handler = objectB.updateUI)

Mais j'ai donné mon avis et je comprend tes réponses. Je pense donc **que l'on peut clore l'issue**.

> Après rien nous empêche de bosser sur un autre article, tout les deux, pour aller plus loin ?

Comme je l'ai dit dans mon premier message, je ne connais ni Swift, ni le développement mobile, 
je pense donc que je serais totalement inutile dans l'article ! 

Bonne continuation, Xavier.
