### ISSUE TITLE
Proposition d'article: Introduction à Vue.js

### ISSUE THREAD

**Issue by sysmoh** [putaindecode/putaindecode.io#754]
Hello!
J'aime vraiment beaucoup, mais beaucoup ce que vous faites ici, c'est vraiment cool de voir une communauté active de français qui font du contenu stylé! Du coup si y'a moyen d'amener mon grain c'est avec plaisir
Dans le plan ce serait:
## Présentation
Petite présentation de vue, d'où il vient, son historique, le côté full open source
## Forces et faiblesses
Notamment son approche full components ainsi que ses libs officielles (routeur, store), et dans ses faiblesses entre autre l'absence cruelle de solution mobile native en opposition à react native ou nativescript pour angular (y'a weex qui approche mais on y est pas encore)
## Créer une petite application
Juste un petit goodies qui va pomper une API quelconque et qui en fait quelque chose de cool, comme les derniers commits de putaindecode, en intégrant le routeur, mais en illustrant bien les concepts du framework
 ## Les autres trucs importants
Le store, les transitions etc.

**Comment by bloodyowl** [comment]
Ce serait top 👍

**Comment by Macxim** [comment]
Go go go!

**Comment by bloodyowl** [comment]
Tu penses que tu pourrais avoir ça de prêt pour quand ? (juste histoire de savoir où le placer sur le planning)

**Comment by skinnyfoetusboy** [comment]
C'est une super initiative 👍

**Comment by sysmoh** [comment]
Yes merci! 
@bloodyowl Alors je m'y mets de suite, mais je suis encore aux études et j'ai jamais fait ça avant, je te redis d'ici ce week-end si ça joue

**Comment by magsout** [comment]
Cool comme article.

**Comment by bloodyowl** [comment]
any news?

**Comment by sysmoh** [comment]
Hey!
Vraiment désolé j'ai pas mal dégusté aux études ces temps j'avais mis en pause, j'aurai fini d'ici mardi-mercredi prochain!

**Comment by MoOx** [comment]
Closed by #774
