### ISSUE TITLE
Post : respecter semver (presque) sans avoir à y penser avec semantic-release

### ISSUE THREAD

**Issue by drazik** [putaindecode/putaindecode.io#758]
Salut,

J'ai essayé [semantic-release](https://github.com/semantic-release/semantic-release) récemment, et je me suis dis qu'en faire un post pourrait être cool car c'est un très bon outil.

Je propose la structure suivante : 

1. Petit rappel : semver, c'est quoi déjà ?
Lien avec [le post déjà existant sur semver](http://putaindecode.io/fr/articles/semver/). Cette partie doit être assez rapide du fait qu'un post exhaustif existe déjà sur p! et que la personne qui s'intéresse à semantic-release doit déjà connaître le principe de semver.

2. Publier un module sur npm manuellement
Description du processus de publication "manuel" d'un module npm (en gros `npm version` puis `npm publish`) et mise en évidence des problèmes qui peuvent intervenir lors de ce processus (incrémenter la version mineure au lieu de majeure à cause d'un oubli ou d'une erreur, par exemple).

3. semantic-release, pour ne plus se soucier de rien, sauf ce sur quoi on travaille
Présentation de semantic-release, du principe d'utiliser un format spécifique de message de commit afin d'automatiser la gestion de semver

4. Exemple de mise en place de semantic-release
Exemple concret d'utilisation de semantic-release sur un projet de module npm (setup, utilisation de travis avec lien possible vers les articles déjà existants sur p!, potentiel de personnalisation, plugins...)

Voilà, à dispo pour en discuter si ça vous parait intéressant :)

**Comment by bloodyowl** [comment]
go 😃

**Comment by MoOx** [comment]
Nice!

**Comment by drazik** [comment]
Je vous propose un premier draft demain alors

**Comment by drazik** [comment]
@bloodyowl @MoOx vous verriez ce post plutôt dans `content/fr/articles/npm` ou dans `content/fr/articles/semver` ?

**Comment by bloodyowl** [comment]
plutôt dans `semver` je dirais

**Comment by MoOx** [comment]
Idem.

**Comment by bloodyowl** [comment]
merged in prod
