### ISSUE TITLE
Message d'accueil et topbar trop grande sur iPhone

### ISSUE THREAD

**Issue by leolelego** [putaindecode/putaindecode.io#759]
Sur iPhone et surement Android le message d'accueil `Putain de code est un site ou vous pouvez...` prend vraiment trop de place. Et le top bar aussi. 

Pour la top bar par exemple en mobile, ceci serait plus "sympa" (ceci est juste une idée)

Logo | Articles | Contribuer | Burger pour les réseaux sociaux -> le tout sur la meme ligne

Et pour le message d'accueil un petit bouton "infos" qui agrandir la vu en accordéon pour voir le texte, par exemple. 

PS: sur iPad aussi le message d'accueil est trop grand, mais le menu ça va. 

<img width="375" alt="image 2" src="https://user-images.githubusercontent.com/4069471/32920455-9a9b2ac6-cb29-11e7-87dd-6969e5df3eb5.png">

**Comment by bloodyowl** [comment]
yes, c'est pris en compte dans la refonte en cours :)

**Comment by MoOx** [comment]
Ouais la refonte va changer ça :)
