### ISSUE TITLE
Post : découverte de Preact

### ISSUE THREAD

**Issue by drazik** [putaindecode/putaindecode.io#769]
Je vous propose d'écrire un post de découverte de Preact. Voici l'idée de base : 

Cet article est destiné aux gens qui connaissent déjà au moins un petit peu React.

Preact est décrit comme étant une "Fast 3kB alternative to React with the same ES6 API."

Ok, mais il doit bien y avoir des compromis, des différences, sinon il aurait totalement enterré React depuis longtemps.

## Quelles sont les différences en React et Preact ?

Ce qu'il "manque" :

* Preact se concentre uniquement sur le DOM. Pas de preact-native, preact-vr ou quoi que ce soit, du coup
* Pas de gestion des PropTypes
* Pas de système de synthetic events. Preact visant uniquement le navigateur, il utilise le système d'events du navigateur

Ce qui est différent :

* Le système de DOM diffing de Preact utilise la librairie `hyperscript`
* `render` reçoit `this.props` et `this.state` en paramètres
* L'API `context` est gérée, mais il n'existe pas de `contextTypes`, `childContextTypes`. Tous les enfants reçoivent les context définit dans `getChildContext()`
* Dans Preact, `props.children` est un `Array`
* Il est possible d'utiliser l'attribut `class` sur un noeud JSX, au lieu de `className` (qui est tout de même supporté)

## Comment démarrer un projet Preact ?

Le plus simple est d'utiliser `preact-cli` => exemple d'utilisation

## J'utilise React, je peux switcher sur Preact ?

Oui, deux solutions :

* `preact-compat` + alias webpack (`react` => `preact-compat` / `react-dom` => `preact-compat`). Mais tu perds l'argument du poids de Preact, puisque tu ajoute une couche de compatibilité (et donc les Ko qui vont avec)
* Faire quelques search/replace, utiliser le bon pragma, virer les PropTypes, modifier un peu l'utilisation de `context`... ça nécessite un peu plus de boulot, mais tu auras une app plus légère

**Comment by MoOx** [comment]
Bonne idée!

**Comment by drazik** [comment]
👍 je me lance dans l'écriture, je propose une PR d'ici la fin de la semaine.
