### ISSUE TITLE
Post: du responsive sans media queries, ça vous dit?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.io#771]
En gros parler de flex-basis et faire un template header/body(content/sidebar)/footer "responsive" sans media queries et expliquer le trick.

**Comment by bloodyowl** [comment]
bonne idée 👍

**Comment by mouadennaciri** [comment]
👍

**Comment by MoOx** [comment]
Il va pas tarder, j'ai un draft :)
