### ISSUE TITLE
Post : Découverte de expo et comparaison avec react native

### ISSUE THREAD

**Issue by sabativi** [putaindecode/putaindecode.io#772]
Je propose de faire un post sur la découverte d'[expo](https://expo.io/) afin de développer des applications avec react-native.

Cet article sera un complément à celui déjà fait sur [react-native](http://putaindecode.io/fr/articles/js/react/native/introduction/) 

Expo est décrit comme : 'The fastest way to build an app'. 

J'essayerai d'expliquer en quoi en étant un peu critique par rapport à la tagline commerciale.

### Comment démarrer un projet ?

Ligne de commande ou IDE.

### Les avantages ?

Pas besoin de XCode ni Android studio pour démarrer.
Pas mal de modules out of the box ( Auth facebook, Push notifications, OTA updates, changement de version react native )

### Les limitations ?

Intégration d'un package avec du code natif.
Ecriture d'un code natif de notre côté.

### Comment revenir à un projet react-native 'classique' ?

La commande eject et ces conséquences avec présentations des choix

---

Le tout accompagné d'un petit exemple ou même une vidéo ?

Sachant que après j'aimerais parler de react-native avec GraphQL et notamment le schema first development.

**Comment by MoOx** [comment]
Bonne idée. Je rajouterais dans les inconvénients le côté "code forcément publique" (bien que je me doute bien que plus tard, moyennant des euros, on aura la possibilité de mettre ça en privée)

Par contre j'irais plutôt sur un exemple simple. La vidéo pourquoi pas mais je n'irais clairement pas mettre graphql dedans, ça peut vite faire trop. Ne pas hésiter à faire un autre post dédié 'RN et graphql".

**Comment by sabativi** [comment]
Oui pardon par « après » je voulais dire prochain article.

**Comment by MoOx** [comment]
Toujours chaud?

**Comment by MoOx** [comment]
PR welcome :)
