### ISSUE TITLE
Mettre un signal de difficulté sur les articles

### ISSUE THREAD

**Issue by leolelego** [putaindecode/putaindecode.io#776]
### principe

L'idée serait d'évaluer les articles sur 2/3 niveaux (débutant [...] avancé) par rapport au sujet ou au language. Un petit emoji à coté du nom ou icône suffirait. 

### Pourquoi

1) je suis pas dev JS et il y a beaucoup (principalement) des devs JS ici, et quand je lis vos articles j'en comprends la moitié parce que c'est pas mon domaine. Mais de temps en temps un article est plus accessible pour un non JS ou débutant JS, du coup je/on pourrais/t voir rapidement les articles plus accessible à notre niveau.

2) 2018 est l'année de plus d'articles pour moi (c'est le début d'année on espère plein de chose^^) et mes derniers articles sont plus pour les débutants en Swift pour l'instant et j'aimerai continuer cette suite de `j'apprends le swift avec maman`. Mais ces articles sont moins passionnant à écrire que des articles plus poussé, voir complexe. Donc j'aimerai alterné. Mais si le lecteur débutant Swift va sur le tag `swift` il va se retrouver avec un article de son niveau puis un incompréhensible etc et a risque de "perdre le poisson", plutôt que de se taper toutes la suite de son niveau. 

Ce n'est qu'une idée, qui marche pour moi, peut être que c'est pas cohérents du tout pour vous 😊

**Comment by drazik** [comment]
Je trouve que c'est une bonne idée, mais on va pas avoir un soucis de subjectivité sur l'évaluation du niveau de chaque article ?

**Comment by leolelego** [comment]
On peut, peut-être définir les grandes lignes des niveaux ensemble et ensuite vérifier qu’ils sont bien utiliser comme il faut?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MoOx** [comment]
poke @bloodyowl @zoontek @jojmaht

**Comment by bloodyowl** [comment]
à bien y réfléchir je vois pas un grand intérêt à la chose. la difficulté dépend de facteurs à la fois subjectifs et dépendant de l'expérience et de la spécialisation. et je dirais même que dans le sens où un tel mécanisme ne ferait que "fermer" (e.g. si un article ne correspond pas au niveau que je me donne, je ne le lirai pas), pour moi c'est non.

**Comment by lionelB** [comment]
plutôt que niveau de difficulté, je pense que la notion de pré-requis serait plus intéressante. 
L'avantage à mes yeux est que ca très bien être géré au niveau rédactionnel dans le chapô.

**Comment by bloodyowl** [comment]
les contrib peuvent ajouter un blockquote en début d'article pour répondre à ce besoin.
