### ISSUE TITLE
Réflexion autour des pinailleurs du code

### ISSUE THREAD

**Issue by bbrassart** [putaindecode/putaindecode.io#779]
Salut à tous et déjà merci d'avoir monté Putain de code! 

J'écoutais votre podcast hier et là, j'entends le mot "pinailleur du code", des mecs qui passent leur temps à vérifier et à commenter les PR des autres. J'aurais aimé aborder le sujet et me demander si c'était vraiment un truc récurrent dans les équipes de devs. Je connais des devs qui reviennent de 3 semaines de vacances et qui reviewent toutes les PR, une à une, et viennent chipoter sur des noms de variables de fonction `let`!!! Ils sont sérieux??? 

Ne venant pas directement du monde de l'IT (ça ne fait que quelques années que je code), j'a parfois l'impression qu'il s'agit même d'une sorte de privilège que s'accordent certains devs, en mode "Moi, je connais le code et les autres de la boite, ils n'y connaissent rien". Du coup, ils s'érigent en prophète (si, si, prophète, le mot est lâché, hahaha) et ils ont l'impression d'écrire la Bible alors que le code de tous les jours (web, applis mobiles) n'a finalement pas grand chose de scientifique.

Un autre truc super intéressant, c'est que finalement, ce type d'attitude, c'est un peu (voire carrément) de la psycho-rigidité! Et c'est un truc un peu contraire au code. En tant que devs, on sait que dans 5 ans, on codera sûrement à l'aide d'un nouveau framework de chez Google (no pun intended).

Si c'était possible, j'aurais adoré regrouper 2, 3 personnes et publier l'article sous forme de dialogue, en mode Catharsis de groupe! Ou même pourquoi pas, sous forme de podcast! 

Merci encore pour le bon taff que je vous faites et je serai ravi de pouvoir collaborer avec vous! Ciao!

**Comment by MoOx** [comment]
Je trouve l'idée super bonne. On en a bcp parlé entre nous récemment! Je me demande même si on a pas un podcast qui va arriver sur le sujet... :)

(Spoiler: je trouve ca relou aussi les pinailleurs)

Je suis partant pour un post.

**Comment by MarcLoupias** [comment]
Bonsoir,

je me permets une intervention, le nommage c'est pas du pinaillage, c'est ce qu'il y a de plus important et de plus difficile dans l'écriture d'un bon code, ça détermine absolument tout (avec les tests et c'est complètement lié). Ca n'a absolument **aucun** rapport avec les technos / frameworks / libs utilisées.

**Comment by MoOx** [comment]
Il faut un grain de sel autour de tous les problèmes soulevés. Attention a ne pas sortir du contexte un simple exemple - on sait tous que les choses les plus dures sont 1/ le nommage 2/ l'invalidation de cache ^^. On en trouvera des exemples où des dev pinaillent sur du nommage qui est correcte.
Puis souvent pour ce genre de choses, les gens perdent plus de temps à se "battre" pour avoir raison, plutôt que faire une petite PR que personne pourra refuser (oui c'est ma technique, plutôt que de lancer un débat en code-review d'après merge, je fais une petite PR qui mange pas de pain et qui me prends souvent pas plus de temps que le temps du "débat").

Il y a souvent la façon de faire qui fait qu'on colle des étiquettes de "relous qui pinaillent".

**Comment by MoOx** [comment]
PR welcome :)
