### ISSUE TITLE
Proposition d'article/podcast Arduino

### ISSUE THREAD

**Issue by toxnico** [putaindecode/putaindecode.io#784]
Bonjour à vous, et merci pour Putain de code!

J'écoute toujours votre podcast avec plaisir et même si React Native n'est pas vraiment mon monde, vos discussions sont très appréciables :)

Il me semble qu'un jour vous avez lancé l'idée de parler de la programmation des microcontrôleurs, typiquement Arduino. Si le sujet vous intéresse toujours, je peux être votre homme.

J'ai par publié hier un article sur la programmation non bloquante, mais pour les débutants complets, je pourrais présenter Arduino de façon beaucoup plus générale, ainsi que les contraintes de ce mode de programmation d'assez bas niveau.

Bonne continuation!

Nico ([dirtymarmotte.net](http://dirtymarmotte.net))

**Comment by MoOx** [comment]
Bonne idée!

**Comment by toxnico** [comment]
Cool! Du coup je te laisse en discuter avec tes collègues pour voir comment on pourrait aborder le sujet?

**Comment by drazik** [comment]
Un nouveau sujet intéressant !

**Comment by MoOx** [comment]
@toxnico je pense que tu peux proposer un article directement, pour on peut imaginer ça en 2e temps. Si tu sais pas trop pour le plan, bah propose déjà un plan ici :)

**Comment by toxnico** [comment]
Dac, je vais mettre ça au clair dans ma tête et je posterai un plan ici alors ;)

**Comment by toxnico** [comment]
Salut à vous,
Voici un plan potentiel pour présenter la chose. En espérant que la programmation de bas niveau ne vous rebute pas trop :)

https://nc.dirtymarmotte.net/index.php/s/YuIrqIkP4GEVm4c

**Comment by drazik** [comment]
Tu envisage un seul gros post, ou plusieurs petits ?

**Comment by toxnico** [comment]
Hello,

J'ai ébauché une première partie dans laquelle je ne rentre pas trop dans le dur.
Le but étant de présenter les concepts et quelques fonctions de base sans balancer trop de code.
Ça vous parle?

https://nc.dirtymarmotte.net/index.php/s/WW7sJfpuMBu2biT

A+

**Comment by MoOx** [comment]
Assez fan de l'article! Je connaissais pas du tout ce monde là et là ça m'a parlé!
@bloodyowl @zoontek @skinnyfoetusboy @magsout @Macxim etc vous en pensez quoi?

**Comment by zoontek** [comment]
L'article est vraiment très bien 👍

**Comment by toxnico** [comment]
Merci pour vos retours positifs!
Je ne savais pas si vous accrocheriez, vu qu'on sort pas mal de l'esprit js quand même :)
Mais tant mieux, c'est cool!

Du coup, voici les sources de l'article en markdown. Je me suis rendu compte que les images étaient pétées dans le document précédent, il faudra certainement refaire les liens.

https://nc.dirtymarmotte.net/index.php/s/3pgw3xI6R7IhnfT

Le prochain post sera plus orienté sur la communication entre l'Arduino et des composants externes, ce sera un peu plus poilu :)

**Comment by MoOx** [comment]
Tu te sens de faire une PR directement?

**Comment by toxnico** [comment]
Je fork, j'explore, je tente et tu sauras si ça a marché ;)

**Comment by MoOx** [comment]
Pensez à regarder ça https://github.com/putaindecode/putaindecode.io/blob/master/CONTRIBUTING.md y'a peut etre des trucs utile haha :)

**Comment by toxnico** [comment]
Merci!
Je ne me suis pas forcé, j'ai écrit comme à la maison :)

**Comment by toxnico** [comment]
C'est prévu dans les propriétés de l'utilisateur, d'avoir 2 identifiants distincts entre github et twitter?
j'ai créé mon dirtymarmotte.json, mon compte twitter est dirtymarmotte, mais mon github est toxnico. 
Ya moyen ou bien?

**Comment by toxnico** [comment]
C'est bon, j'ai compris le principe :)

**Comment by MoOx** [comment]
Closed by #785
