### ISSUE TITLE
Plutôt sympa ce site mais bonjour la gestion des écrans !!

### ISSUE THREAD

**Issue by Gercofis** [putaindecode/putaindecode.io#788]
Bonjour a tous je suis tombé sur ce site par hasard !
J'ai du mal a comprendre a l'heure de l'Auto-Layout que ce système ne soit pas pris en compte, il y a tout de même beaucoup de portables, iPad et autres ???

**Comment by Gercofis** [comment]
Bonjour,

Sur un MBP avec Safari… Le texte est a moitié a coté, on s’en sort mais bon…
Vous programmé tous sur des écrans 24 »...

Gilles ROBERT
Hent An Dervenn
63 Ter Route du Gouerest
29570 ROSCANVEL

gillesrobert@free.fr
06 20 68 01 35
09 54 75 81 53

**Comment by MoOx** [comment]
Désolé je ne vois toujours pas de soucis. J'ai un 15" et j'ai fait une toute petite fenetre pour voir.

![image](https://user-images.githubusercontent.com/157534/39882017-e566cd8e-5482-11e8-92b6-8d0d75eecef1.png)

![image](https://user-images.githubusercontent.com/157534/39882028-edcba3e6-5482-11e8-942a-a6f99d99b681.png)

![image](https://user-images.githubusercontent.com/157534/39882042-fa6188f0-5482-11e8-8c73-51c53fd3b818.png)

![image](https://user-images.githubusercontent.com/157534/39882049-04280e18-5483-11e8-98ab-3e7f42e28dce.png)

Avec plus un screenshot on serait plus avancé. Quel version de Safari? Version de macOS? Merci.

**Comment by Gercofis** [comment]
Bonsoir,

Tu vas avoir du mal a me croire mais ce soir tout est redevenu normal comme chez toi…
A moins que tu aies modifié quelque chose ?

Je bricole beaucoup avec Xcode et parfois il y a des trucs bizarres… Mais bon pourtant j’ai un système tout neuf installé sur un SSD neuf, il n’y a que les trucs courants et Xcode. Tout le reste est sur l’ancien DD…

Cordialement - Gilles 

Gilles ROBERT
Hent An Dervenn
63 Ter Route du Gouerest
29570 ROSCANVEL

gillesrobert@free.fr
06 20 68 01 35
09 54 75 81 53

**Comment by MoOx** [comment]
Rien de spécial n'a été fait :)
Tant mieux si tout va bien.

**Comment by Gercofis** [comment]
Bonjour,

Pendant qu’on y est si le pro du Mac pouvait nous faire un Tuto sur CoreData ??

Cordialement - Gilles 

Gilles ROBERT
109c Chemin Saint Vincent
73190 CHALLES LES EAUX
0954758153 - 0620680135
Gillesrobert@free.fr
Tweet : @gercofis
