### ISSUE TITLE
La nouvelle Context Api de React

### ISSUE THREAD

**Issue by neovea** [putaindecode/putaindecode.io#789]
Bonjour, 
je souhaiterais écrire un article à propos de la nouvelle context api de React et d'une implémentation que nous avons mis en place dans ma boîte. Est-ce que ce serait ok ?
Merci

**Comment by bloodyowl** [comment]
sure!

**Comment by magsout** [comment]
carrément, excellente idée

**Comment by MoOx** [comment]
+1

**Comment by desirelabs** [comment]
OK go ;p

**Comment by Essential** [comment]
https://github.com/putaindecode/putaindecode.io/pull/792
