### ISSUE TITLE
Participée à putain de code (Shell)

### ISSUE THREAD

**Issue by x86inside** [putaindecode/putaindecode.io#795]
Salut, j’aimerais publier des postes très cours , sur l’utilisation du shell, car beaucoup d'exemple de code sur le web sont de vrais prise de tête. 
Un exemple vous faite une rechercher sur le web, pour supprimer les espaces dans une ligne. Et là il faut une semaine pour comprendre, ce qui est écris dans les forums. alors que la solution est toute simple  `sed 's/ //' ` et comme j’utilise pas le shell tous les jours, j’écris une fonction que je rajoute à mon fichier outils.sh après je l’utilise en fonctions des besoin.
`maVariable=$(echo $(cat "$(SelectionneFichier $numerosDuFichier)"|sed -n "$numeroDeLigne p"|cut -d"-" -f3-4|SuprimeEspaces)) `

bien cordialement Pascal

**Comment by MoOx** [comment]
Pourquoi pas!

**Comment by MoOx** [comment]
PR welcome :)
