### ISSUE TITLE
Post : Introduction à GraphQL

### ISSUE THREAD

**Issue by ghost** [putaindecode/putaindecode.io#804]
Bonjour,

Je souhaite rédiger une introduction à GraphQL, voire une série d'articles avec un exemple d'implémentation Express/Mongo/GraphQL (le sujet avait déjà été abordé #679).

Qu'en pensez-vous ?

**Comment by MoOx** [comment]
Go

**Comment by lionelB** [comment]
trop bien !

**Comment by magsout** [comment]
👍

**Comment by MoOx** [comment]
PR welcome :)
