### ISSUE TITLE
Post : introduction au Hooks de React

### ISSUE THREAD

**Issue by magsout** [putaindecode/putaindecode.io#805]
J'ai envie de reprendre un peu les articles. 

J'ai bien envie de parler des dernières features de React à savoir `memo`, `Suspense` et `Hooks`.

Avant d'avoir les yeux plus gros que le ventre et ne rien faire (coucou les SVG, tu m'entends ?), on va commencer petit par les Hook.  J'ai déjà un petit draft.

Ca vous dit ? ou pas ?

**Comment by MoOx** [comment]
Gooo

**Comment by brandonsueur** [comment]
do it 👍
