### ISSUE TITLE
Add page timer

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.io#81]
Look at this page and see when scrolling, you've got a timer to display the end time to read it.

http://blog.ponyfoo.com/2013/11/13/grunt-tips-and-tricks

**Comment by madx** [comment]
Y'a plus rien concernant le temps de lecture sur la nouvelle version c'est normal ?

**Comment by MoOx** [comment]
@madx t'es couillon lol => 

# #399

**Comment by MoOx** [comment]
Too old.
