### ISSUE TITLE
The RSS feed seems to be broken and same articles are sent everyday

### ISSUE THREAD

**Issue by blemoine** [putaindecode/putaindecode.io#825]
Since the release of the new website, I receive  the same last ten posts every day in my RSS Reader.

It's probably easy to reproduce: use `http://putaindecode.io/feed.xml` in any RSS reader, and look at it everyday. 

(BTW thanks for the great blog!)

**Comment by bloodyowl** [comment]
that seems weird. the fact that it did that one time after the release is normal (given the URL remapping we did) but I don't see any reason it'd continue to show up as new. 

did you have this behaviour during the last three days? the feed has been untouched in that time

**Comment by blemoine** [comment]
I would say it's started roughly 10 days ago (hard to say exactly when).

Looking at the feed, there is no `pubDate`  in the item. I know it's optional, but it could that my reader (netvibes) use this (optional) information to know when something as been published. 

If the only reader with the problem is netvibes, forget this issue. It would give an excuse to use another RSS Reader.

**Comment by bloodyowl** [comment]
ça devrait être fixed.

hésite pas à rouvrir l'issue si le comportement se reproduit à partir de maintenant.

**Comment by blemoine** [comment]
Merci beaucoup :)
