### ISSUE TITLE
Dark mode : où sont les links ?

### ISSUE THREAD

**Issue by Scriptura** [putaindecode/putaindecode.io#850]
Salut les gars,

Ça fait longtemps que je voulais vous le dire : en mode sombre les liens ne sont plus visibles. Ben oui parce qu'un color #000 sur un background #000...

Cordialement

**Comment by bloodyowl** [comment]
https://github.com/putaindecode/putaindecode.io/commit/f4b5c484d2c2f0bcf30be655baeab0503dfc4d1b
