### ISSUE TITLE
Encore un ou deux trucs à propos du design

### ISSUE THREAD

**Issue by Scriptura** [putaindecode/putaindecode.io#851]
Re salut les gars,

Parce que vous avez été réactifs pour corriger un artefact signalé hier, encore un ou deux trucs :
- les encarts CodePen font péter le layout des pages de votre site sur mobile. Allez voir l'article dédié au responsive with flexbox ;)
- les PNG transparents/traits noirs en mode dark et ben... on les voit pas.
- un dernier point, que l'on retrouve sur beaucoup de blogs de dev' mais plus rarement sur celui d'un intégrateur/UX/UI/truc (comme c'est étrange) : le texte justifié sous petites résolutions. Comment dire... c'est immonde. Pour moi ce n'est pas vraiment subjectif mais à vous de voir.

**Comment by MoOx** [comment]
@Scriptura  en effet sur l'article responsive, certain pen on été hardcodé avec une largeur, exprès, car sinon les exemples "desktop" sur mobile... auront la vue mobile, ce qui va à l'encontre du principe du post. 
Il n'y en a que 2 je crois et ça a donc été fait exprès.

Pour les PNGs c'est un soucis en effet. Idem la justification imo.
